#nullable disable

using System.Collections.Generic;
using System.Linq;

namespace HlidacStatu.Entities
{
    public class ObecStats
    {
        public enum Attrs
        {
            Bankomat,
            Brownfield,
            COV_sms,
            Dum_pro_seniory,
            Dum_s_pecovatelskou_sluzbou,
            Hasicska_zbrojnice,
            Herna,
            Hospic,
            Hrbitov,
            Infocentrum,
            Kulturni_objekt,
            LDN,
            Lekarna,
            Most,
            Obchod_s_potravinami,
            Obecni_urad,
            Ordinace_lekare,
            Parkoviste,
            Policejni_stanice,
            Posta,
            Restaurace,
            Rybniky_nadrze,
            Sber_recyklovatelneho_odpadu,
            Sberny_dvur,
            Skladovy_areal,
            Skola,
            Sportoviste,
            Trafostanice,
            Vodojem,
            Nadmorska_vyska,
            Katastralni_plocha,
            Pocet_linek_dalkovych,
            Pocet_linek_mistniho_vyznamu,
            Pocet_linek_mestske_dopravy,
            Pocet_linek_MHD_autobusove,
            Pocet_linek_MHD_tramvaje,
            Pocet_linek_MHD_metro,
            Pocet_zastavek_dalkovych_linek,
            Pocet_zastavek_mistniho_vyznamu,
            Pocet_zastavek_mestske_dopravy,
            Pocet_zastavek_MHD_autobusy,
            Pocet_zastavek_MHD_tramvaje,
            Pocet_zastavek_MHD_metro,
            Pocet_vlakovych_trati,
            Posta_pocet,
            Postovni_smerovaci_cislo,
            Verejny_rozhlas,
            Verejny_vodovod,
            Kanalizace,
            COV,
            Hasic_zachr_sbor_vc_pl_zav_utv,
            Hasicsky_zachranny_sbor_pocet_sboru,
            Sbor_dobrov_has_obce_vc_dobr_z_u,
            Pozarni_nadrz,
            Pozarni_hydrant_podz_i_nadz,
            Obvodni_odd_policie,
            Mestska_obecni_policie,
            Plynofikace_obce,
            Skladka_komunalnich_odpadu,
            Spolec_zariz_mater_skoly_a_jesle,
            Materska_skola_CSU_,
            Zakl_skola_pouze_s_1_st_CSU_,
            Zakl_skola_s_1_a_2_st_CSU_,
            Zakl_skola_pouze_s_2_st_CSU_,
            Zakladni_skola,
            Stredni_odborne_uciliste_vc_zdravotn_,
            Gymnazium,
            Konzervatore_CSU_,
            Stredni_integrovana_skola,
            Skoly_specialni_dr_pro_ml_vyz_zvl_peci_,
            Zakladni_umelecka_skola,
            Vysoka_skola,
            Fakulty_VS,
            Jazykove_skoly_s_pravem_stat_zkousky_CSU_,
            Vyssi_odborna_skola_CSU_,
            Detsky_domov,
            Verejna_knihovna_vc_pobocek,
            Divadlo,
            Prirodni_amfiteatry_vc_let_kin_,
            Muzeum_vcetne_pobocek_a_sam_pam_,
            Galerie_vc_pobocek_a_vystavnich_sini_,
            Kulturni_zarizeni_ostat_,
            Stredisko_pro_volny_cas_deti_a_mladeze,
            Zoologicka_zahrada,
            Sakralni_stavba,
            Hrbitov_sms,
            Krematorium,
            Smutecni_sin,
            Koupaliste_a_bazeny_s_prov_sprav_,
            Kryte_bazeny_z_koupalist_a_bazenu,
            Hriste_s_provozovatelem_nebo_spr_,
            Telocvicny_vc_skolnich_s_prist_verej_,
            Stadiony_otevrene,
            Stadiony_kryte,
            Zimni_stadiony_kryte_i_otevrene,
            Sdruzena_ambulantni_zarizeni,
            Zdravotni_strediska,
            Nemocnice,
            Lecebna_pro_dlouhodobe_nemocne,
            Ostatni_luzkova_zarizeni,
            Detas_pracoviste_ostat_luz_zarizeni,
            Samost_ord_prakt_lek_pro_dospele,
            Detas_prac_sam_ordin_prakt_lek_pro_dosp_,
            Samost_ord_prakt_lek_pro_deti_a_dorost,
            Det_prac_sam_ord_prak_lek_pro_deti_a_dor,
            Samost_ord_prakt_lek_stomatologa,
            Det_prac_sam_ord_prakt_lek_stomatologa,
            Samost_ord_prakt_lek_gynekologa,
            Detas_prac_sam_ord_prakt_lek_gynekologa,
            Samost_ord_lekare_specialisty,
            Detas_prac_sam_ord_lekare_specialisty,
            Ostatni_samostatna_zarizeni,
            Detas_prac_ostatniho_samostat_zarizeni,
            Zarizeni_lekarenske_pece_lekarny_,
            Detas_pracoviste_zariz_lekarenske_pece,
            Veterinarni_osetrovny_pocet_vc_soukr_,
            Jesle,
            Kojenecky_ustav,
            Detsky_domov_2,
            Dalsi_detska_zarizeni,
            Stred_zachr_sluzby_a_rych_zdr_pom_,
            Okresni_zdravotni_ustav,
            Transfusni_stanice,
            Benzinove_cerpaci_stanice,
            Penezni_ustavy_a_jejich_uradovny,
            Pojistovny_a_jejich_uradovny,
            Financni_urady,
            Ustavy_socialni_pece_pro_dospele,
            Vesnicky_SOS,
            Domov_pro_matky_s_detmi,
            Kino,
            Kulturni_dum_sal_pro_poradani_spolecenskych_akci,
            Turisticke_informacni_centrum,
            Stredisko_pro_volny_cas_deti_a_mladeze_2,
            Kostel_s_nabozenskym_vyuzitim,
            Koupaliste,
            Kryty_bazen,
            Hriste,
            Detske_hriste,
            Viceucelova_telocvicna_sokolovna_sportovni_hala,
            Jednoucelove_kryte_sportovni_zarizeni,
            Zive_narozeni,
            Zemreli,
            Prirozeny_prirustek,
            Pristehovali,
            Vystehovali,
            Prumerny_vek_zijicich_zeny,
            Prumerny_vek_zijicich_muzi,
            Obyvatelstvo_celkem,
            Obyvatelstvo_celkem_zeny,
            Obyvatelstvo_celkem_muzi,
            Obyvatelstvo_vek_0_5_celkem,
            Obyvatelstvo_vek_6_14_celkem,
            Obyvatelstvo_vek_15_24_celkem,
            Obyvatelstvo_vek_25_39_celkem,
            Obyvatelstvo_vek_40_54_celkem,
            Obyvatelstvo_vek_55_64_celkem,
            Obyvatelstvo_vek_nezjisten_celkem,
            Obyvatelstvo_vek_65_a_vice_celkem,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_zakladni_vc_neukonc_celkem,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_str_vc_vyuc_bez_mat_celk,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_uplne_stredni_s_mat_celkem,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_nast_a_vyssi_odb_vzd_celkem,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_vysokoskolske_celkem,
            Obyvatelstvo_vek_15_a_vice_vc_nezj_nejvyssi_uk_vzdel_nezjisteno

        }
        static Dictionary<Attrs, string> AttrsToStr = new Dictionary<Attrs, string>()
        {
            { Attrs.Bankomat, "sms_1"},
            { Attrs.Brownfield, "sms_2"},
            { Attrs.COV_sms, "sms_3"},
            { Attrs.Dum_pro_seniory, "sms_4"},
            { Attrs.Dum_s_pecovatelskou_sluzbou, "sms_5"},
            { Attrs.Hasicska_zbrojnice, "sms_6"},
            { Attrs.Herna, "sms_7"},
            { Attrs.Hospic, "sms_8"},
            { Attrs.Hrbitov_sms, "sms_9"},
            { Attrs.Infocentrum, "sms_10"},
            { Attrs.Kulturni_objekt, "sms_11"},
            { Attrs.LDN, "sms_12"},
            { Attrs.Lekarna, "sms_13"},
            { Attrs.Most, "sms_14"},
            { Attrs.Obchod_s_potravinami, "sms_15"},
            { Attrs.Obecni_urad, "sms_16"},
            { Attrs.Ordinace_lekare, "sms_17"},
            { Attrs.Parkoviste, "sms_18"},
            { Attrs.Policejni_stanice, "sms_19"},
            { Attrs.Posta, "sms_20"},
            { Attrs.Restaurace, "sms_21"},
            { Attrs.Rybniky_nadrze, "sms_22"},
            { Attrs.Sber_recyklovatelneho_odpadu, "sms_23"},
            { Attrs.Sberny_dvur, "sms_24"},
            { Attrs.Skladovy_areal, "sms_25"},
            { Attrs.Skola, "sms_26"},
            { Attrs.Sportoviste, "sms_27"},
            { Attrs.Trafostanice, "sms_28"},
            { Attrs.Vodojem, "sms_29"},
            { Attrs.Nadmorska_vyska, "10200"},
            { Attrs.Katastralni_plocha, "10300"},
            { Attrs.Pocet_linek_dalkovych, "20100"},
            { Attrs.Pocet_linek_mistniho_vyznamu, "20200"},
            { Attrs.Pocet_linek_mestske_dopravy, "20300"},
            { Attrs.Pocet_linek_MHD_autobusove, "20310"},
            { Attrs.Pocet_linek_MHD_tramvaje, "20320"},
            { Attrs.Pocet_linek_MHD_metro, "20330"},
            { Attrs.Pocet_zastavek_dalkovych_linek, "20400"},
            { Attrs.Pocet_zastavek_mistniho_vyznamu, "20500"},
            { Attrs.Pocet_zastavek_mestske_dopravy, "20600"},
            { Attrs.Pocet_zastavek_MHD_autobusy, "20620"},
            { Attrs.Pocet_zastavek_MHD_tramvaje, "20630"},
            { Attrs.Pocet_zastavek_MHD_metro, "20640"},
            { Attrs.Pocet_vlakovych_trati, "20700"},
            { Attrs.Posta_pocet, "30100"},
            { Attrs.Postovni_smerovaci_cislo, "30110"},
            { Attrs.Verejny_rozhlas, "30300"},
            { Attrs.Verejny_vodovod, "30500"},
            { Attrs.Kanalizace, "30620"},
            { Attrs.COV, "30630"},
            { Attrs.Hasic_zachr_sbor_vc_pl_zav_utv, "30700"},
            { Attrs.Hasicsky_zachranny_sbor_pocet_sboru, "30710"},
            { Attrs.Sbor_dobrov_has_obce_vc_dobr_z_u, "30800"},
            { Attrs.Pozarni_nadrz, "30900"},
            { Attrs.Pozarni_hydrant_podz_i_nadz, "30910"},
            { Attrs.Obvodni_odd_policie, "31100"},
            { Attrs.Mestska_obecni_policie, "31120"},
            { Attrs.Plynofikace_obce, "31200"},
            { Attrs.Skladka_komunalnich_odpadu, "32100"},
            { Attrs.Spolec_zariz_mater_skoly_a_jesle, "40200"},
            { Attrs.Materska_skola_CSU_, "40300"},
            { Attrs.Zakl_skola_pouze_s_1_st_CSU_, "40400"},
            { Attrs.Zakl_skola_s_1_a_2_st_CSU_, "40500"},
            { Attrs.Zakl_skola_pouze_s_2_st_CSU_, "40540"},
            { Attrs.Zakladni_skola, "40590"},
            { Attrs.Stredni_odborne_uciliste_vc_zdravotn_, "40600"},
            { Attrs.Gymnazium, "40700"},
            { Attrs.Konzervatore_CSU_, "40830"},
            { Attrs.Stredni_integrovana_skola, "40850"},
            { Attrs.Skoly_specialni_dr_pro_ml_vyz_zvl_peci_, "40900"},
            { Attrs.Zakladni_umelecka_skola, "41000"},
            { Attrs.Vysoka_skola, "41050"},
            { Attrs.Fakulty_VS, "41100"},
            { Attrs.Jazykove_skoly_s_pravem_stat_zkousky_CSU_, "41200"},
            { Attrs.Vyssi_odborna_skola_CSU_, "41300"},
            { Attrs.Detsky_domov, "41400"},
            { Attrs.Verejna_knihovna_vc_pobocek, "50100"},
            { Attrs.Divadlo, "50300"},
            { Attrs.Prirodni_amfiteatry_vc_let_kin_, "50400"},
            { Attrs.Muzeum_vcetne_pobocek_a_sam_pam_, "50500"},
            { Attrs.Galerie_vc_pobocek_a_vystavnich_sini_, "50600"},
            { Attrs.Kulturni_zarizeni_ostat_, "50700"},
            { Attrs.Stredisko_pro_volny_cas_deti_a_mladeze, "50800"},
            { Attrs.Zoologicka_zahrada, "50900"},
            { Attrs.Sakralni_stavba, "51000"},
            { Attrs.Hrbitov, "51100"},
            { Attrs.Krematorium, "51110"},
            { Attrs.Smutecni_sin, "51120"},
            { Attrs.Koupaliste_a_bazeny_s_prov_sprav_, "60100"},
            { Attrs.Kryte_bazeny_z_koupalist_a_bazenu, "60110"},
            { Attrs.Hriste_s_provozovatelem_nebo_spr_, "60200"},
            { Attrs.Telocvicny_vc_skolnich_s_prist_verej_, "60210"},
            { Attrs.Stadiony_otevrene, "60300"},
            { Attrs.Stadiony_kryte, "60310"},
            { Attrs.Zimni_stadiony_kryte_i_otevrene, "60400"},
            { Attrs.Sdruzena_ambulantni_zarizeni, "70100"},
            { Attrs.Zdravotni_strediska, "70200"},
            { Attrs.Nemocnice, "70300"},
            { Attrs.Lecebna_pro_dlouhodobe_nemocne, "70500"},
            { Attrs.Ostatni_luzkova_zarizeni, "70600"},
            { Attrs.Detas_pracoviste_ostat_luz_zarizeni, "70601"},
            { Attrs.Samost_ord_prakt_lek_pro_dospele, "70700"},
            { Attrs.Detas_prac_sam_ordin_prakt_lek_pro_dosp_, "70701"},
            { Attrs.Samost_ord_prakt_lek_pro_deti_a_dorost, "70710"},
            { Attrs.Det_prac_sam_ord_prak_lek_pro_deti_a_dor, "70711"},
            { Attrs.Samost_ord_prakt_lek_stomatologa, "70720"},
            { Attrs.Det_prac_sam_ord_prakt_lek_stomatologa, "70721"},
            { Attrs.Samost_ord_prakt_lek_gynekologa, "70730"},
            { Attrs.Detas_prac_sam_ord_prakt_lek_gynekologa, "70731"},
            { Attrs.Samost_ord_lekare_specialisty, "70740"},
            { Attrs.Detas_prac_sam_ord_lekare_specialisty, "70741"},
            { Attrs.Ostatni_samostatna_zarizeni, "70800"},
            { Attrs.Detas_prac_ostatniho_samostat_zarizeni, "70801"},
            { Attrs.Zarizeni_lekarenske_pece_lekarny_, "71000"},
            { Attrs.Detas_pracoviste_zariz_lekarenske_pece, "71001"},
            { Attrs.Veterinarni_osetrovny_pocet_vc_soukr_, "71100"},
            { Attrs.Jesle, "71200"},
            { Attrs.Kojenecky_ustav, "71300"},
            { Attrs.Detsky_domov_2, "71400"},
            { Attrs.Dalsi_detska_zarizeni, "71500"},
            { Attrs.Stred_zachr_sluzby_a_rych_zdr_pom_, "71600"},
            { Attrs.Okresni_zdravotni_ustav, "71700"},
            { Attrs.Transfusni_stanice, "71800"},
            { Attrs.Benzinove_cerpaci_stanice, "81100"},
            { Attrs.Penezni_ustavy_a_jejich_uradovny, "100200"},
            { Attrs.Pojistovny_a_jejich_uradovny, "100400"},
            { Attrs.Financni_urady, "100500"},
            { Attrs.Ustavy_socialni_pece_pro_dospele, "150100"},
            { Attrs.Vesnicky_SOS, "150135"},
            { Attrs.Domov_pro_matky_s_detmi, "150137"},
            { Attrs.Kino, "600801"},
            { Attrs.Kulturni_dum_sal_pro_poradani_spolecenskych_akci, "600802"},
            { Attrs.Turisticke_informacni_centrum, "600803"},
            { Attrs.Stredisko_pro_volny_cas_deti_a_mladeze_2, "600804"},
            { Attrs.Kostel_s_nabozenskym_vyuzitim, "600805"},
            { Attrs.Koupaliste, "600806"},
            { Attrs.Kryty_bazen, "600807"},
            { Attrs.Hriste, "600808"},
            { Attrs.Detske_hriste, "600809"},
            { Attrs.Viceucelova_telocvicna_sokolovna_sportovni_hala, "600810"},
            { Attrs.Jednoucelove_kryte_sportovni_zarizeni, "600811"},
            { Attrs.Zive_narozeni, "110200"},
            { Attrs.Zemreli, "110300"},
            { Attrs.Prirozeny_prirustek, "110350"},
            { Attrs.Pristehovali, "110400"},
            { Attrs.Vystehovali, "110500"},
            { Attrs.Prumerny_vek_zijicich_zeny, "113010"},
            { Attrs.Prumerny_vek_zijicich_muzi, "113020"},
            { Attrs.Obyvatelstvo_celkem, "420101"},
            { Attrs.Obyvatelstvo_celkem_zeny, "420102"},
            { Attrs.Obyvatelstvo_celkem_muzi, "420103"},
            { Attrs.Obyvatelstvo_vek_0_5_celkem, "410201"},
            { Attrs.Obyvatelstvo_vek_6_14_celkem, "410202"},
            { Attrs.Obyvatelstvo_vek_15_24_celkem, "410203"},
            { Attrs.Obyvatelstvo_vek_25_39_celkem, "410204"},
            { Attrs.Obyvatelstvo_vek_40_54_celkem, "410205"},
            { Attrs.Obyvatelstvo_vek_55_64_celkem, "410206"},
            { Attrs.Obyvatelstvo_vek_nezjisten_celkem, "410207"},
            { Attrs.Obyvatelstvo_vek_65_a_vice_celkem, "410208"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_zakladni_vc_neukonc_celkem, "410301"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_str_vc_vyuc_bez_mat_celk, "410302"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_uplne_stredni_s_mat_celkem, "410303"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_nast_a_vyssi_odb_vzd_celkem, "410304"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_vysokoskolske_celkem, "410305"},
            { Attrs.Obyvatelstvo_vek_15_a_vice_vc_nezj_nejvyssi_uk_vzdel_nezjisteno, "410306"},
        };

        public class ValueYear
        {
            public int? Year { get; set; }
            public decimal? Value { get; set; }
        }
        public class Attr : ObceZUJAttr
        {
            public ObceZUJAttrName AttrName { get; set; }
        }

        public ObceZUJ Obec { get; set; }
        public Attr[] Stats { get; set; }

        private decimal? GetVal(string attrKey)
        {
            return GetValYear(attrKey)?.Value;
        }
        private ValueYear GetValYear(string attrKey)
        {
            return GetValYears(attrKey).FirstOrDefault() ?? null;
        }
        private IEnumerable<ValueYear> GetValYears(string attrKey)
        {
            if (Stats == null)
                return new ValueYear[] { };

            return Stats
                .Where(m => m.Key == attrKey)
                .Select(m => new ValueYear() { Year = m.Year, Value = m.Value })
                .OrderByDescending(m => m.Year);
        }
    }
}
