//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ufal.UDPipe {

public class EmptyNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EmptyNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EmptyNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EmptyNode obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EmptyNode() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          udpipe_csharpPINVOKE.delete_EmptyNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int id {
    set {
      udpipe_csharpPINVOKE.EmptyNode_id_set(swigCPtr, value);
    } 
    get {
      int ret = udpipe_csharpPINVOKE.EmptyNode_id_get(swigCPtr);
      return ret;
    } 
  }

  public int index {
    set {
      udpipe_csharpPINVOKE.EmptyNode_index_set(swigCPtr, value);
    } 
    get {
      int ret = udpipe_csharpPINVOKE.EmptyNode_index_get(swigCPtr);
      return ret;
    } 
  }

  public string form {
    set {
      udpipe_csharpPINVOKE.EmptyNode_form_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_form_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string lemma {
    set {
      udpipe_csharpPINVOKE.EmptyNode_lemma_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_lemma_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string upostag {
    set {
      udpipe_csharpPINVOKE.EmptyNode_upostag_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_upostag_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string xpostag {
    set {
      udpipe_csharpPINVOKE.EmptyNode_xpostag_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_xpostag_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string feats {
    set {
      udpipe_csharpPINVOKE.EmptyNode_feats_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_feats_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string deps {
    set {
      udpipe_csharpPINVOKE.EmptyNode_deps_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_deps_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string misc {
    set {
      udpipe_csharpPINVOKE.EmptyNode_misc_set(swigCPtr, value);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = udpipe_csharpPINVOKE.EmptyNode_misc_get(swigCPtr);
      if (udpipe_csharpPINVOKE.SWIGPendingException.Pending) throw udpipe_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public EmptyNode(int id, int index) : this(udpipe_csharpPINVOKE.new_EmptyNode__SWIG_0(id, index), true) {
  }

  public EmptyNode(int id) : this(udpipe_csharpPINVOKE.new_EmptyNode__SWIG_1(id), true) {
  }

  public EmptyNode() : this(udpipe_csharpPINVOKE.new_EmptyNode__SWIG_2(), true) {
  }

}

}
