//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace HlidacStatu.Lib.Data.External.StatniPokladna.PrispevkoveOrg
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [XmlRoot("ciselnik_UCJED_export")]
    [XmlType("ciselnik_UCJED_export")]
    public partial class ucjed_export
    {

        private ucjed_xml[] rowField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public ucjed_xml[] row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ucjed_xml
    {

        private long ucjed_idField;

        private string csuis_ucjed_idField;

        private string icoField;

        private string start_dateField;

        private string end_dateField;

        private string nazevField;

        private string dicField;

        private string adresaField;

        private string uliceField;

        private string sidloField;

        private string pscField;

        private string zrizovatel_idField;

        private string zrizovatel_icoField;

        private string pocobField;

        private string krajField;

        private string obecField;

        private string konecplatField;

        private string datumvznikuField;

        private string datumaktField;

        private string kapitola_idField;

        private string druhuj_idField;

        private string poddruhuj_idField;

        private string katobyv_idField;

        private string forma_idField;

        private string aktorg_idField;

        private string nace_idField;

        private string nuts_idField;

        private string cofog_idField;

        private string isektor_idField;

        private string druhrizeni_idField;

        private string stat_idField;

        private string typorg_idField;

        private string zdrojfin_idField;

        private string zpodm_idField;

        private string veduc_idField;

        private string orp_idField;

        private string pou_idField;

        private string zuj_idField;

        /// <remarks/>
        public long ucjed_id
        {
            get
            {
                return this.ucjed_idField;
            }
            set
            {
                this.ucjed_idField = value;
            }
        }

        /// <remarks/>
        public string csuis_ucjed_id
        {
            get
            {
                return this.csuis_ucjed_idField;
            }
            set
            {
                this.csuis_ucjed_idField = value;
            }
        }

        /// <remarks/>
        public string ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }

        /// <remarks/>
        public string start_date
        {
            get
            {
                return this.start_dateField;
            }
            set
            {
                this.start_dateField = value;
            }
        }

        /// <remarks/>
        public string end_date
        {
            get
            {
                return this.end_dateField;
            }
            set
            {
                this.end_dateField = value;
            }
        }

        /// <remarks/>
        public string nazev
        {
            get
            {
                return this.nazevField;
            }
            set
            {
                this.nazevField = value;
            }
        }

        /// <remarks/>
        public string dic
        {
            get
            {
                return this.dicField;
            }
            set
            {
                this.dicField = value;
            }
        }

        /// <remarks/>
        public string adresa
        {
            get
            {
                return this.adresaField;
            }
            set
            {
                this.adresaField = value;
            }
        }

        /// <remarks/>
        public string ulice
        {
            get
            {
                return this.uliceField;
            }
            set
            {
                this.uliceField = value;
            }
        }

        /// <remarks/>
        public string sidlo
        {
            get
            {
                return this.sidloField;
            }
            set
            {
                this.sidloField = value;
            }
        }

        /// <remarks/>
        public string psc
        {
            get
            {
                return this.pscField;
            }
            set
            {
                this.pscField = value;
            }
        }

        /// <remarks/>
        public string zrizovatel_id
        {
            get
            {
                return this.zrizovatel_idField;
            }
            set
            {
                this.zrizovatel_idField = value;
            }
        }

        /// <remarks/>
        public string zrizovatel_ico
        {
            get
            {
                return this.zrizovatel_icoField;
            }
            set
            {
                this.zrizovatel_icoField = value;
            }
        }

        /// <remarks/>
        public string pocob
        {
            get
            {
                return this.pocobField;
            }
            set
            {
                this.pocobField = value;
            }
        }

        /// <remarks/>
        public string kraj
        {
            get
            {
                return this.krajField;
            }
            set
            {
                this.krajField = value;
            }
        }

        /// <remarks/>
        public string obec
        {
            get
            {
                return this.obecField;
            }
            set
            {
                this.obecField = value;
            }
        }

        /// <remarks/>
        public string konecplat
        {
            get
            {
                return this.konecplatField;
            }
            set
            {
                this.konecplatField = value;
            }
        }

        /// <remarks/>
        public string datumvzniku
        {
            get
            {
                return this.datumvznikuField;
            }
            set
            {
                this.datumvznikuField = value;
            }
        }

        /// <remarks/>
        public string datumakt
        {
            get
            {
                return this.datumaktField;
            }
            set
            {
                this.datumaktField = value;
            }
        }

        /// <remarks/>
        public string kapitola_id
        {
            get
            {
                return this.kapitola_idField;
            }
            set
            {
                this.kapitola_idField = value;
            }
        }

        /// <remarks/>
        public string druhuj_id
        {
            get
            {
                return this.druhuj_idField;
            }
            set
            {
                this.druhuj_idField = value;
            }
        }

        /// <remarks/>
        public string poddruhuj_id
        {
            get
            {
                return this.poddruhuj_idField;
            }
            set
            {
                this.poddruhuj_idField = value;
            }
        }

        /// <remarks/>
        public string katobyv_id
        {
            get
            {
                return this.katobyv_idField;
            }
            set
            {
                this.katobyv_idField = value;
            }
        }

        /// <remarks/>
        public string forma_id
        {
            get
            {
                return this.forma_idField;
            }
            set
            {
                this.forma_idField = value;
            }
        }

        /// <remarks/>
        public string aktorg_id
        {
            get
            {
                return this.aktorg_idField;
            }
            set
            {
                this.aktorg_idField = value;
            }
        }

        /// <remarks/>
        public string nace_id
        {
            get
            {
                return this.nace_idField;
            }
            set
            {
                this.nace_idField = value;
            }
        }

        /// <remarks/>
        public string nuts_id
        {
            get
            {
                return this.nuts_idField;
            }
            set
            {
                this.nuts_idField = value;
            }
        }

        /// <remarks/>
        public string cofog_id
        {
            get
            {
                return this.cofog_idField;
            }
            set
            {
                this.cofog_idField = value;
            }
        }

        /// <remarks/>
        public string isektor_id
        {
            get
            {
                return this.isektor_idField;
            }
            set
            {
                this.isektor_idField = value;
            }
        }

        /// <remarks/>
        public string druhrizeni_id
        {
            get
            {
                return this.druhrizeni_idField;
            }
            set
            {
                this.druhrizeni_idField = value;
            }
        }

        /// <remarks/>
        public string stat_id
        {
            get
            {
                return this.stat_idField;
            }
            set
            {
                this.stat_idField = value;
            }
        }

        /// <remarks/>
        public string typorg_id
        {
            get
            {
                return this.typorg_idField;
            }
            set
            {
                this.typorg_idField = value;
            }
        }

        /// <remarks/>
        public string zdrojfin_id
        {
            get
            {
                return this.zdrojfin_idField;
            }
            set
            {
                this.zdrojfin_idField = value;
            }
        }

        /// <remarks/>
        public string zpodm_id
        {
            get
            {
                return this.zpodm_idField;
            }
            set
            {
                this.zpodm_idField = value;
            }
        }

        /// <remarks/>
        public string veduc_id
        {
            get
            {
                return this.veduc_idField;
            }
            set
            {
                this.veduc_idField = value;
            }
        }

        /// <remarks/>
        public string orp_id
        {
            get
            {
                return this.orp_idField;
            }
            set
            {
                this.orp_idField = value;
            }
        }

        /// <remarks/>
        public string pou_id
        {
            get
            {
                return this.pou_idField;
            }
            set
            {
                this.pou_idField = value;
            }
        }

        /// <remarks/>
        public string zuj_id
        {
            get
            {
                return this.zuj_idField;
            }
            set
            {
                this.zuj_idField = value;
            }
        }
    }
}