// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class dbCtx : DbContext
{
    public dbCtx(DbContextOptions<dbCtx> options)
        : base(options)
    {
    }

    public virtual DbSet<TechnickeProhlidky> TechnickeProhlidkies { get; set; }

    public virtual DbSet<VlastnikProvozovatelVozidla> VlastnikProvozovatelVozidlas { get; set; }

    public virtual DbSet<VozidlaDoplnkoveVybaveni> VozidlaDoplnkoveVybavenis { get; set; }

    public virtual DbSet<VozidlaDovoz> VozidlaDovozs { get; set; }

    public virtual DbSet<VozidlaVyrazenaZProvozu> VozidlaVyrazenaZProvozus { get; set; }

    public virtual DbSet<VypisVozidel> VypisVozidels { get; set; }

    public virtual DbSet<ZpravyVyrobceZastupce> ZpravyVyrobceZastupces { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TechnickeProhlidky>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("technicke_prohlidky");

            entity.HasIndex(e => e.Pcv, "IX_technicke_prohlidky_PCV");

            entity.Property(e => e.CisloProtokolu).HasColumnName("Cislo_protokolu");
            entity.Property(e => e.KodStk)
                .HasColumnType("money")
                .HasColumnName("Kod_STK");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.NazevStk).HasColumnName("Nazev_STK");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
            entity.Property(e => e.PlatnostDo).HasColumnName("Platnost_do");
            entity.Property(e => e.PlatnostOd).HasColumnName("Platnost_od");
        });

        modelBuilder.Entity<VlastnikProvozovatelVozidla>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("vlastnik_provozovatel_vozidla");

            entity.HasIndex(e => e.Pcv, "IX_vlastnik_provozovatel_vozidla_PCV");

            entity.Property(e => e.DatumDo).HasColumnName("Datum_do");
            entity.Property(e => e.DatumOd).HasColumnName("Datum_od");
            entity.Property(e => e.Ico).HasColumnName("ICO");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
            entity.Property(e => e.TypSubjektu)
                .HasColumnType("money")
                .HasColumnName("Typ_subjektu");
            entity.Property(e => e.VztahKVozidlu)
                .HasColumnType("money")
                .HasColumnName("Vztah_k_vozidlu");
        });

        modelBuilder.Entity<VozidlaDoplnkoveVybaveni>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("vozidla_doplnkove_vybaveni");

            entity.HasIndex(e => e.Pcv, "IX_vozidla_doplnkove_vybaveni_PCV");

            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
        });

        modelBuilder.Entity<VozidlaDovoz>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("vozidla_dovoz");

            entity.HasIndex(e => e.Pcv, "IX_vozidla_dovoz_PCV");

            entity.Property(e => e.DatumDovozu).HasColumnName("Datum_dovozu");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
        });

        modelBuilder.Entity<VozidlaVyrazenaZProvozu>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("vozidla_vyrazena_z_provozu");

            entity.HasIndex(e => e.Pcv, "IX_vozidla_vyrazena_z_provozu_PCV");

            entity.Property(e => e.DatumDo).HasColumnName("Datum_do");
            entity.Property(e => e.DatumOd).HasColumnName("Datum_od");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
            entity.Property(e => e.RmKod)
                .HasColumnType("money")
                .HasColumnName("RM_kod");
            entity.Property(e => e.RmNazev).HasColumnName("RM_Nazev");
        });

        modelBuilder.Entity<VypisVozidel>(entity =>
        {
            entity.HasKey(e => e.Pcv);

            entity.ToTable("vypis_vozidel");

            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
            entity.Property(e => e.CheckSum)
                .HasMaxLength(50)
                .HasColumnName("CheckSum");
            entity.Property(e => e.Abs).HasColumnName("ABS");
            entity.Property(e => e.AlternativniProvedeni).HasColumnName("Alternativni_provedeni");
            entity.Property(e => e.Asr).HasColumnName("ASR");
            entity.Property(e => e.BrzdyNouzova).HasColumnName("Brzdy_nouzova");
            entity.Property(e => e.BrzdyOdlehcovaci).HasColumnName("Brzdy_odlehcovaci");
            entity.Property(e => e.BrzdyParkovaci).HasColumnName("Brzdy_parkovaci");
            entity.Property(e => e.BrzdyProvozni).HasColumnName("Brzdy_provozni");
            entity.Property(e => e.CisloMotoru).HasColumnName("Cislo_motoru");
            entity.Property(e => e.CisloOrv).HasColumnName("Cislo_ORV");
            entity.Property(e => e.CisloTp).HasColumnName("Cislo_TP");
            entity.Property(e => e.Co2Mesto)
                .HasColumnType("money")
                .HasColumnName("CO2_mesto");
            entity.Property(e => e.Co2MimoMesto)
                .HasColumnType("money")
                .HasColumnName("CO2_mimo_mesto");
            entity.Property(e => e.DalsiZaznamy).HasColumnName("Dalsi_zaznamy");
            entity.Property(e => e.Datum1Registrace).HasColumnName("Datum_1_registrace");
            entity.Property(e => e.Datum1RegistraceVCr).HasColumnName("Datum_1_registrace_v_CR");
            entity.Property(e => e.Delka).HasColumnType("money");
            entity.Property(e => e.DelkaDo)
                //.HasColumnType("money")
                .HasColumnName("Delka_do");
            entity.Property(e => e.DojezdZr)
                .HasColumnType("money")
                .HasColumnName("Dojezd_ZR");
            entity.Property(e => e.DoplňkovyTextNaTp).HasColumnName("Doplňkovy_text_na_TP");
            entity.Property(e => e.DruhKaroserie).HasColumnName("Druh_karoserie");
            entity.Property(e => e.DruhRz).HasColumnName("Druh_RZ");
            entity.Property(e => e.DruhVozidla).HasColumnName("Druh_vozidla");
            entity.Property(e => e.DruhVozidla2Radek).HasColumnName("Druh_vozidla_2_radek");
            entity.Property(e => e.EsEu).HasColumnName("ES_EU");
            entity.Property(e => e.FaktorOdchylkyDe)
                .HasColumnType("money")
                .HasColumnName("Faktor_odchylky_DE");
            entity.Property(e => e.FaktorVerifikaceVf)
                .HasColumnType("money")
                .HasColumnName("Faktor_verifikace_Vf");
            entity.Property(e => e.HmotnostiProvozniDo)
                .HasColumnName("Hmotnosti_provozni_Do");
            entity.Property(e => e.HmotnostiVozidlaPriTestuWltp).HasColumnName("Hmotnosti_vozidla_pri_testu_WLTP");
            entity.Property(e => e.HmotnostiZatizeniSz)
                .HasColumnType("money")
                .HasColumnName("Hmotnosti_zatizeni_SZ");
            entity.Property(e => e.HmotnostiZatizeniSzTyp).HasColumnName("Hmotnosti_zatizeni_SZ_typ");
            entity.Property(e => e.HybridniVozidlo).HasColumnName("Hybridni_vozidlo");
            entity.Property(e => e.InovativniTechnologie).HasColumnName("Inovativni_technologie");
            entity.Property(e => e.KategorieVozidla).HasColumnName("Kategorie_vozidla");
            entity.Property(e => e.KolaNaprava1).HasColumnName("Kola_naprava_1");
            entity.Property(e => e.KolaNaprava2).HasColumnName("Kola_naprava_2");
            entity.Property(e => e.KolaNaprava3).HasColumnName("Kola_naprava_3");
            entity.Property(e => e.KolaNaprava4).HasColumnName("Kola_naprava_4");
            entity.Property(e => e.KorigovanySoucinitelAbsorpce)
                .HasColumnType("money")
                .HasColumnName("Korigovany_soucinitel_absorpce");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LoznaDelka)
                .HasColumnType("money")
                .HasColumnName("Lozna_delka");
            entity.Property(e => e.LoznaSirka)
                .HasColumnType("money")
                .HasColumnName("Lozna_sirka");
            entity.Property(e => e.MaxVykon)
                .HasColumnType("money")
                .HasColumnName("Max_vykon");
            entity.Property(e => e.NapravPohanenych).HasColumnName("Naprav_pohanenych");
            entity.Property(e => e.NejvetsiPovolenaHmotnostJizdniSoupravy)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_povolena_hmotnost_jizdni_soupravy");
            entity.Property(e => e.NejvetsiPovolenaHmotnostNaNapravuN1).HasColumnName("Nejvetsi_povolena_hmotnost_na_napravu_N1");
            entity.Property(e => e.NejvetsiPovolenaHmotnostNaNapravuN2).HasColumnName("Nejvetsi_povolena_hmotnost_na_napravu_N2");
            entity.Property(e => e.NejvetsiPovolenaHmotnostNaNapravuN3).HasColumnName("Nejvetsi_povolena_hmotnost_na_napravu_N3");
            entity.Property(e => e.NejvetsiPovolenaHmotnostNaNapravuN4).HasColumnName("Nejvetsi_povolena_hmotnost_na_napravu_N4");
            entity.Property(e => e.NejvetsiPovolenaHmotnostPripojnehoVozidlaBrzdene)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_povolena_hmotnost_pripojneho_vozidla_brzdene");
            entity.Property(e => e.NejvetsiPovolenaHmotnostPripojnehoVozidlaNeBrzdene)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_povolena_hmotnost_pripojneho_vozidla_ne_brzdene");
            entity.Property(e => e.NejvetsiTechnickyPovolenaHmotnost)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_technicky_povolena_hmotnost");
            entity.Property(e => e.NejvetsiTechnickyPripustnaHmotnost)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_technicky_pripustna_hmotnost");
            entity.Property(e => e.NejvetsiTechnickyPripustnaHmotnostJizdniSoupravy)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_technicky_pripustna_hmotnost_jizdni_soupravy");
            entity.Property(e => e.NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaBrzdene)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_technicky_pripustna_hmotnost_pripojneho_vozidla_brzdene");
            entity.Property(e => e.NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaNeBrzdene)
                .HasColumnType("money")
                .HasColumnName("Nejvetsi_technicky_pripustna_hmotnost_pripojneho_vozidla_ne_brzdene");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN1).HasColumnName("Nejvetsi_technicky_pripustna_povolena_hmotnost_na_napravu_N1");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN2).HasColumnName("Nejvetsi_technicky_pripustna_povolena_hmotnost_na_napravu_N2");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN3).HasColumnName("Nejvetsi_technicky_pripustna_povolena_hmotnost_na_napravu_N3");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN4).HasColumnName("Nejvetsi_technicky_pripustna_povolena_hmotnost_na_napravu_N4");
            entity.Property(e => e.NejvyssiRychlost)
                .HasColumnType("money")
                .HasColumnName("Nejvyssi_rychlost");
            entity.Property(e => e.NejvyssiRychlostOmezeni)
                .HasColumnType("money")
                .HasColumnName("Nejvyssi_rychlost_omezeni");
            entity.Property(e => e.ObchodniOznaceni).HasColumnName("Obchodni_oznaceni");
            entity.Property(e => e.ObjemCisterny)
                //.HasColumnType("money")
                .HasColumnName("Objem_cisterny");
            entity.Property(e => e.Otacky).HasColumnType("money");
            entity.Property(e => e.OvladaniBrzdSz).HasColumnName("Ovladani_brzd_SZ");
            entity.Property(e => e.OvladaniBrzdSzDruh).HasColumnName("Ovladani_brzd_SZ_druh");
            entity.Property(e => e.PlneElektrickeVozidlo).HasColumnName("Plne_elektricke_vozidlo");
            entity.Property(e => e.PneumatikyNaprava1).HasColumnName("Pneumatiky_naprava_1");
            entity.Property(e => e.PneumatikyNaprava2).HasColumnName("Pneumatiky_naprava_2");
            entity.Property(e => e.PneumatikyNaprava3).HasColumnName("Pneumatiky_naprava_3");
            entity.Property(e => e.PneumatikyNaprava4).HasColumnName("Pneumatiky_naprava_4");
            entity.Property(e => e.PocetMistCelkem)
                .HasColumnType("money")
                .HasColumnName("Pocet_mist_celkem");
            entity.Property(e => e.PocetMistKSezeni)
                .HasColumnType("money")
                .HasColumnName("Pocet_mist_k_sezeni");
            entity.Property(e => e.PocetMistKStani)
                .HasColumnType("money")
                .HasColumnName("Pocet_mist_k_stani");
            entity.Property(e => e.PocetNaprav)
                .HasColumnType("money")
                .HasColumnName("Pocet_naprav");
            entity.Property(e => e.PomerVykonHmotnost)
                .HasColumnType("money")
                .HasColumnName("Pomer_vykon_hmotnost");

            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostRaw).HasColumnName("NejvetsiTechnickyPripustnaPovolenaHmotnostRaw");
            entity.Property(e => e.SpotrebaRaw).HasColumnName("SpotrebaRaw");
            entity.Property(e => e.EmisniLimitRaw).HasColumnName("EmisniLimitRaw");
            entity.Property(e => e.PocetMistRaw).HasColumnName("PocetMistRaw");
            entity.Property(e => e.CelkovaDelkaSirkaVyskaRaw).HasColumnName("CelkovaDelkaSirkaVyskaRaw");
            entity.Property(e => e.RozchodRaw).HasColumnName("RozchodRaw");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuRaw).HasColumnName("NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuRaw");
            entity.Property(e => e.NejvetsiPovolenaHmotnostNaNapravuRaw).HasColumnName("NejvetsiPovolenaHmotnostNaNapravuRaw");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaBrzdeneRaw).HasColumnName("NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaBrzdeneRaw");
            entity.Property(e => e.NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaNebrzdeneRaw).HasColumnName("NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaNebrzdeneRaw");
            entity.Property(e => e.PocetNapravRaw).HasColumnName("PocetNapravRaw");
            entity.Property(e => e.KolaPneumatikyNapravyRaw).HasColumnName("KolaPneumatikyNapravyRaw");
            entity.Property(e => e.VnejsiHlukVozidlaStojiciRaw).HasColumnName("VnejsiHlukVozidlaStojiciRaw");
            entity.Property(e => e.VnejsiHlukVozidlaZaJizdyRaw).HasColumnName("VnejsiHlukVozidlaZaJizdyRaw");
            entity.Property(e => e.Co2Raw).HasColumnName("Co2Raw");


            entity.Property(e => e.PredpisEhkOsn).HasColumnName("Predpis_EHK_OSN");
            entity.Property(e => e.PredpisEhsEsEu).HasColumnName("Predpis_EHS_ES_EU");
            entity.Property(e => e.PredpisSpotrebaPaliva).HasColumnName("Predpis_spotreba_paliva");
            entity.Property(e => e.ProvozniHmotnost)
                //.HasColumnType("money")
                .HasColumnName("Provozni_hmotnost");
            entity.Property(e => e.PrumernaHodnotaUzitecnehoZatizeni)
                .HasColumnType("money")
                .HasColumnName("Prumerna_hodnota_uzitecneho_zatizeni");
            entity.Property(e => e.RmZaniku).HasColumnName("RM_zaniku");
            entity.Property(e => e.RokVyroby)
                //.HasColumnType("money")
                .HasColumnName("Rok_vyroby");
            entity.Property(e => e.Rozchod1)
                .HasColumnType("money")
                .HasColumnName("Rozchod_1");
            entity.Property(e => e.Rozchod2)
                .HasColumnType("money")
                .HasColumnName("Rozchod_2");
            entity.Property(e => e.Rozchod3)
                .HasColumnType("money")
                .HasColumnName("Rozchod_3");
            entity.Property(e => e.Rozchod4)
                .HasColumnType("money")
                .HasColumnName("Rozchod_4");
            entity.Property(e => e.RozvorRaw)
                //.HasColumnType("money")
                .HasColumnName("RozvorRaw");
            entity.Property(e => e.Sirka).HasColumnType("money");
            entity.Property(e => e.SnizeniEmisiNedc)
                .HasColumnType("money")
                .HasColumnName("Snizeni_emisi_NEDC");
            entity.Property(e => e.SnizeniEmisiWltp)
                .HasColumnType("money")
                .HasColumnName("Snizeni_emisi_WLTP");
            entity.Property(e => e.SpecifickeCo2Raw)
                //.HasColumnType("money")
                .HasColumnName("SpecifickeCo2Raw");
            entity.Property(e => e.SpojovaciZarizeni).HasColumnName("Spojovaci_zarizeni");
            entity.Property(e => e.SpotrebaElMobil)
                .HasColumnType("money")
                .HasColumnName("Spotreba_el_mobil");
            entity.Property(e => e.SpotrebaKombinovana)
                .HasColumnType("money")
                .HasColumnName("Spotreba_kombinovana");
            entity.Property(e => e.SpotrebaMesto)
                .HasColumnType("money")
                .HasColumnName("Spotreba_mesto");
            entity.Property(e => e.SpotrebaMimoMesto)
                .HasColumnType("money")
                .HasColumnName("Spotreba_mimo_mesto");
            entity.Property(e => e.SpotrebaPriRychlosti).HasColumnName("Spotreba_pri_rychlosti");
            entity.Property(e => e.StupenDokonceni).HasColumnName("Stupen_dokonceni");
            entity.Property(e => e.StupenPlneniEmisniUrovne).HasColumnName("Stupen_plneni_emisni_urovne");
            entity.Property(e => e.TovarniZnacka).HasColumnName("Tovarni_znacka");
            entity.Property(e => e.TridaHybridnihoVozidla).HasColumnName("Trida_hybridniho_vozidla");
            entity.Property(e => e.TypKod).HasColumnName("Typ_kod");
            entity.Property(e => e.TypMotoru).HasColumnName("Typ_motoru");
            entity.Property(e => e.UcelVozidla).HasColumnName("Ucel_vozidla");
            entity.Property(e => e.Vin).HasColumnName("VIN");
            entity.Property(e => e.VnejsiHlukVozidlaJizda)
                .HasColumnType("money")
                .HasColumnName("Vnejsi_hluk_vozidla_jizda");
            entity.Property(e => e.VnejsiHlukVozidlaOtacky)
                .HasColumnType("money")
                .HasColumnName("Vnejsi_hluk_vozidla_otacky");
            entity.Property(e => e.VnejsiHlukVozidlaStojici)
                .HasColumnType("money")
                .HasColumnName("Vnejsi_hluk_vozidla_stojici");
            entity.Property(e => e.VyrobceKaroserie).HasColumnName("Vyrobce_karoserie");
            entity.Property(e => e.VyrobceMotoru).HasColumnName("Vyrobce_motoru");
            entity.Property(e => e.VyrobceVozidla).HasColumnName("Vyrobce_vozidla");
            entity.Property(e => e.VyrobniCisloKaroserie).HasColumnName("Vyrobni_cislo_karoserie");
            entity.Property(e => e.Vyska).HasColumnType("money");
            entity.Property(e => e.VyskaDo)
                //.HasColumnType("money")
                .HasColumnName("Vyska_do");
            entity.Property(e => e.ZadrzenaRzPosledni).HasColumnName("Zadrzena_RZ_posledni");
            entity.Property(e => e.ZadrzenoOrv).HasColumnName("Zadrzeno_ORV");
            entity.Property(e => e.ZarazeniVozidla).HasColumnName("Zarazeni_vozidla");
            entity.Property(e => e.ZatizeniStrechy).HasColumnName("Zatizeni_strechy");
            entity.Property(e => e.ZdvihovyObjem)
                //.HasColumnType("money")
                .HasColumnName("Zdvihovy_objem");
            entity.Property(e => e.Ztp).HasColumnName("ZTP");
        });

        modelBuilder.Entity<ZpravyVyrobceZastupce>(entity =>
        {
            entity.HasKey(e => e.Pk);

            entity.ToTable("zpravy_vyrobce_zastupce");

            entity.HasIndex(e => e.Pcv, "IX_zpravy_vyrobce_zastupce_PCV");

            entity.Property(e => e.KratkyText).HasColumnName("Kratky_text");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Pcv)
                .HasMaxLength(30)
                .HasColumnName("PCV");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}