// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace HlidacStatu.RegistrVozidel.Models
{
    public interface ICheckDuplicate
    {
        public enum DuplicateCheckResult
        {
            NoDuplicate = 0,
            SamePrimaryKeyOtherChecksum = 1,
            Same = 1,
        }
        //string ComputeCheckSum();
        static abstract Task PreDuplication();
        static abstract Task PostDuplication();
        Task<DuplicateCheckResult> CheckDuplicateAsync();
        

    }
}