// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class TechnickeProhlidky
{
    public string Pcv { get; set; }

    public string Typ { get; set; }

    public string Stav { get; set; }

    public decimal? KodStk { get; set; }

    public string NazevStk { get; set; }

    public DateOnly? PlatnostOd { get; set; }

    public DateOnly? PlatnostDo { get; set; }

    public string CisloProtokolu { get; set; }

    public bool? Aktualni { get; set; }

    public DateOnly LastUpdated { get; set; }

    public long Pk { get; set; }
}