// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

//CSV Header:
//PČV,Typ,Stav,Kód STK,Název STK,Platnost od,Platnost do,Číslo protokolu,Aktuální
public partial class TechnickeProhlidky : ICheckDuplicate
{
    static HashSet<string> _uniqueKeys = new();
    public async static Task PreDuplication()
    {
        if (_uniqueKeys.Count > 0)
            return;
        using var db = new dbCtx();
        db.Database.SetCommandTimeout(TimeSpan.FromSeconds(180));
        _uniqueKeys = await db.TechnickeProhlidky
            .AsNoTracking()
            .Select(m => $"{m.Pcv}\t{m.CheckSum}")
            .ToHashSetAsync();

        //await Task.CompletedTask;
    }
    public async static Task PostDuplication()
    {
        _uniqueKeys.Clear();

        //await Task.CompletedTask;
    }

    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        if (_uniqueKeys == null)
            throw new InvalidOperationException("PreDuplication must be called before CheckDuplicateAsync.");
        var key = this.Pcv + "\t" + this.CheckSum;
        if (_uniqueKeys.Contains(key) == false)
            return DuplicateCheckResult.NoDuplicate;
        else
            return DuplicateCheckResult.Same;

    }

    [Name("PČV")]
    public string Pcv { get; set; }
    [Name("Typ")]
    public string Typ { get; set; }

    [Name("Stav")]
    public string Stav { get; set; }

    [Name("Kód STK")]
    public decimal? KodStk { get; set; }

    [Name("Název STK")]
    public string NazevStk { get; set; }

    [Name("Platnost od")]
    public DateOnly? PlatnostOd { get; set; }

    [Name("Platnost do")]
    public DateOnly? PlatnostDo { get; set; }

    [Name("Číslo protokolu")]
    public string CisloProtokolu { get; set; }

    [Name("Aktuální")]
    public bool? Aktualni { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}