// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// PČV,Typ subjektu,Vztah k vozidlu,Aktuální,IČO,Název,Adresa,Datum od,Datum do
public partial class VlastnikProvozovatelVozidla : ICheckDuplicate
{
    static Dictionary<string, string> _uniqueKeys = new();
    public async static Task PreDuplication()
    {
        if (_uniqueKeys.Count > 0)
            return;
        using var db = new dbCtx();
        _uniqueKeys = await db.VlastnikProvozovatelVozidla
            .AsNoTracking()
            .Select(m => new { pk = m.Pcv, checksum = m.CheckSum })
            .ToDictionaryAsync(k => k.pk, v => v.checksum);

        //await Task.CompletedTask;
    }
    public async static Task PostDuplication()
    {
        _uniqueKeys.Clear();

        //await Task.CompletedTask;
    }
    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        var existQ = _uniqueKeys
            .Where(m => m.Key == this.Pcv)
            .Where(m => m.Value == this.CheckSum)
            .Select(m => new { pk = m.Key, checksum = m.Value });

        var exist = existQ
            .FirstOrDefault();

        if (exist == null)
            return DuplicateCheckResult.NoDuplicate;
        else if (exist.checksum != this.CheckSum)
            return DuplicateCheckResult.NoDuplicate; //add new record even if PK is same but checksum differ
        else
            return DuplicateCheckResult.Same;
    }

    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Typ subjektu")]
    public decimal? TypSubjektu { get; set; }

    [Name("Vztah k vozidlu")]
    public decimal? VztahKVozidlu { get; set; }

    [Name("Aktuální")]
    public bool? Aktualni { get; set; }

    [Name("IČO")]
    public string Ico { get; set; }

    [Name("Název")]
    public string Nazev { get; set; }

    [Name("Adresa")]
    public string Adresa { get; set; }

    [Name("Datum od")]
    public DateOnly? DatumOd { get; set; }

    [Name("Datum do")]
    public DateOnly? DatumDo { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}