// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// PČV,Typ subjektu,Vztah k vozidlu,Aktuální,IČO,Název,Adresa,Datum od,Datum do
public partial class VlastnikProvozovatelVozidla
{
    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Typ subjektu")]
    public decimal? TypSubjektu { get; set; }

    [Name("Vztah k vozidlu")]
    public decimal? VztahKVozidlu { get; set; }

    [Name("Aktuální")]
    public bool? Aktualni { get; set; }

    [Name("IČO")]
    public string Ico { get; set; }

    [Name("Název")]
    public string Nazev { get; set; }

    [Name("Adresa")]
    public string Adresa { get; set; }

    [Name("Datum od")]
    public DateOnly? DatumOd { get; set; }

    [Name("Datum do")]
    public DateOnly? DatumDo { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
}