// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Devmasters.Enums;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// PČV,Typ subjektu,Vztah k vozidlu,Aktuální,IČO,Název,Adresa,Datum od,Datum do
public partial class VlastnikProvozovatelVozidla : ICheckDuplicate
{
    static HashSet<string> _uniqueKeys = new();
    public async static Task PreDuplication()
    {
        if (_uniqueKeys.Count > 0)
            return;
        using var db = new dbCtx();
        db.Database.SetCommandTimeout(TimeSpan.FromSeconds(180));
        _uniqueKeys = await db.VlastnikProvozovatelVozidla
            .AsNoTracking()
            .Select(m => $"{m.Pcv}\t{m.CheckSum}")
            .ToHashSetAsync();

        //await Task.CompletedTask;
    }
    public async static Task PostDuplication()
    {
        _uniqueKeys.Clear();

        //await Task.CompletedTask;
    }

    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        if (_uniqueKeys == null)
            throw new InvalidOperationException("PreDuplication must be called before CheckDuplicateAsync.");
        var key = this.Pcv + "\t" + this.CheckSum;
        if (_uniqueKeys.Contains(key) == false)
            return DuplicateCheckResult.NoDuplicate;
        else
            return DuplicateCheckResult.Same;
    }

    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Typ subjektu")]
    public decimal? TypSubjektu { get; set; }

    [Name("Vztah k vozidlu")]
    public decimal? VztahKVozidlu { get; set; }



    [Ignore]
    public Enums.Vztah_k_vozidluEnum FormaVlastnictvi { get => (Enums.Vztah_k_vozidluEnum)(VztahKVozidlu ?? 0); }

    [Name("Aktuální")]
    public bool? Aktualni { get; set; }

    [Name("IČO")]
    public string Ico { get; set; }

    [Name("Název")]
    public string Nazev { get; set; }

    [Name("Adresa")]
    public string Adresa { get; set; }

    [Name("Datum od")]
    public DateOnly? DatumOd { get; set; }

    [Name("Datum do")]
    public DateOnly? DatumDo { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}