// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaVyrazenaZProvozu
{
    public string Pcv { get; set; }

    public DateOnly? DatumOd { get; set; }

    public DateOnly? DatumDo { get; set; }

    public string Duvod { get; set; }

    public decimal? RmKod { get; set; }

    public string RmNazev { get; set; }

    public DateOnly LastUpdated { get; set; }

    public long Pk { get; set; }
}