// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaDoplnkoveVybaveni : ICheckDuplicate
{
    static HashSet<string> _uniqueKeys = new();
    public async static Task PreDuplication()
    {
        if (_uniqueKeys.Count > 0)
            return;
        using var db = new dbCtx();
        db.Database.SetCommandTimeout(TimeSpan.FromSeconds(180));
        _uniqueKeys = await db.VozidlaDoplnkoveVybaveni
            .AsNoTracking()
            .Select(m => $"{m.Pcv}\t{m.CheckSum}")
            .ToHashSetAsync();

        //await Task.CompletedTask;
    }
    public async static Task PostDuplication()
    {
        _uniqueKeys.Clear();

        //await Task.CompletedTask;
    }

    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        if (_uniqueKeys == null)
            throw new InvalidOperationException("PreDuplication must be called before CheckDuplicateAsync.");
        var key = this.Pcv + "\t" + this.CheckSum;
        if (_uniqueKeys.Contains(key) == false)
            return DuplicateCheckResult.NoDuplicate;
        else
            return DuplicateCheckResult.Same;
    }

    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Typ")]
    public string Typ { get; set; }

    [Name("Od")]
    public DateOnly? Od { get; set; }

    [Name("Do")]
    public DateOnly? Do { get; set; }

    public DateOnly LastUpdated { get; set; }

    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}