// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaDovoz
{
    public string Pcv { get; set; }

    public string Stat { get; set; }

    public DateOnly? DatumDovozu { get; set; }

    public DateOnly LastUpdated { get; set; }

    public long Pk { get; set; }
}