// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// PČV,Datum od,Datum do,Důvod,RM kód,RM Název
public partial class VozidlaVyrazenaZProvozu : ICheckDuplicate
{
    public async static Task PreDuplication()
    {
        await Task.CompletedTask;
    }
    public async static Task PostDuplication()
    {
        await Task.CompletedTask;
    }

    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        using var db = new dbCtx();
        var existQ = db.VozidlaVyrazenaZProvozu
            .AsNoTracking()
            .Where(m => m.Pcv == this.Pcv && m.CheckSum == this.CheckSum)
            .Select(m => new { pk = m.Pcv, checksum = m.CheckSum });

        var exist = await existQ
            .FirstOrDefaultAsync();

        if (exist == null)
            return DuplicateCheckResult.NoDuplicate;
        else if (exist.checksum != this.CheckSum)
            return DuplicateCheckResult.NoDuplicate; //add new record even if PK is same but checksum differ
        else
            return DuplicateCheckResult.Same;
    }

    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Datum od")]
    public DateOnly? DatumOd { get; set; }

    [Name("Datum do")]
    public DateOnly? DatumDo { get; set; }

    [Name("Důvod")]
    public string Duvod { get; set; }

    [Name("RM kód")]
    public decimal? RmKod { get; set; }

    [Name("RM Název")]
    public string RmNazev { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}