// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.ICheckDuplicate;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaDovoz : ICheckDuplicate
{
    public async Task<DuplicateCheckResult> CheckDuplicateAsync()
    {
        using var db = new dbCtx();
        var existQ = db.VypisVozidel
            .AsNoTracking()
            .Where(m => m.Pcv == this.Pcv)
            .Select(m => new { pk = m.Pcv, checksum = m.CheckSum });

        var exist = await existQ
            .FirstOrDefaultAsync();

        if (exist == null)
            return DuplicateCheckResult.NoDuplicate;
        else if (exist.checksum != this.CheckSum)
            return DuplicateCheckResult.NoDuplicate; //add new record even if PK is same but checksum differ
        else
            return DuplicateCheckResult.Same;
    }
    [Name("PČV")]
    public string Pcv { get; set; }


    [Name("Stát")]
    public string Stat { get; set; }

    [Name("Datum dovozu")]
    public DateOnly? DatumDovozu { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
    string _checksum = null;
    public string CheckSum
    {
        get
        {
            if (_checksum == null)
            {
                _checksum = Util.ComputeCheckSum(this);
            }
            return _checksum;
        }
        set { _checksum = value; }
    }
}