// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// PČV,Datum od,Datum do,Důvod,RM kód,RM Název
public partial class VozidlaVyrazenaZProvozu
{
    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Datum od")]
    public DateOnly? DatumOd { get; set; }

    [Name("Datum do")]
    public DateOnly? DatumDo { get; set; }

    [Name("Důvod")]
    public string Duvod { get; set; }

    [Name("RM kód")]
    public decimal? RmKod { get; set; }

    [Name("RM Název")]
    public string RmNazev { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
}