// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaDovoz
{
    [Name("PČV")]
    public string Pcv { get; set; }


    [Name("Stát")]
    public string Stat { get; set; }

    [Name("Datum dovozu")]
    public DateOnly? DatumDovozu { get; set; }

    [Ignore]
    public DateOnly LastUpdated { get; set; }

    [Ignore]
    public long Pk { get; set; }
}