// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VozidlaDoplnkoveVybaveni
{
    [Name("PČV")]
    public string Pcv { get; set; }

    [Name("Typ")]
    public string Typ { get; set; }

    [Name("Od")]
    public DateOnly? Od { get; set; }

    [Name("Do")]
    public DateOnly? Do { get; set; }

    public DateOnly LastUpdated { get; set; }

    public long Pk { get; set; }
}