// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;
using static HlidacStatu.RegistrVozidel.Models.CSVConverters;

namespace HlidacStatu.RegistrVozidel.Models;

// CSV Header:
// Datum 1  registrace,Datum 1  registrace v ČR,ZTP,ES EU,Druh vozidla,Druh vozidla 2  ř ,Kategorie vozidla,Tovární značka,
// Typ,Varianta,Verze,VIN,Obchodní označení,Výrobce vozidla,Výrobce motoru,Typ motoru,Max  výkon  kW     min⁻¹ ,
// Palivo,Zdvihový objem  cm³ ,Plně elektrické vozidlo,Hybridní vozidlo,Třída hybridního vozidla,Emisní limit  EHKOSN EHSES ,
// Stupeň plnění emisní úrovně,Korigovaný součinitel absorbce  m⁻¹ ,CO2 město  mimo město kombinované  g km-1 ,
// Specifické CO2,Snížení emisí – NEDC,Snížení emisí – WLTP,Spotřeba předpis,Spotřeba město  mimo město kombinovaná  l 100km⁻¹ ,
// Spotřeba při rychlosti  l 100 km⁻¹ ,Spotřeba el  mobil  Wh km  – Z,Dojezd ZR  km ,Výrobce karoserie,Druh (typ),
// Výrobní číslo karoserie,Barva,Barva doplňková,Počet míst celkem   k sezení   k stání,Celková délka šířka výška  mm ,
// Rozvor  mm ,Rozchod  mm ,Provozní hmotnost,Největší technicky přípustná povolená hmotnost  kg ,
// Největší technicky přípustná povolená hmotnost na nápravu  kg ,
// Největší technicky přípustná povolená hmotnost přípojného vozidla  kg  brzděného,
// Největší technicky přípustná povolená hmotnost přípojného vozidla  kg  nebrzděného,
// Největší technicky přípustná povolená hmotnost jízdní soupravy  kg ,
// Hmotnosti vozidla při testu WLTP,Průměrná hodnota užitečného zatížení,Spojovací zařízení - druh,
// Počet náprav - z toho poháněných,Kola a pneumatiky na nápravě - rozměry montáž  N 1; N 2; N 3; N 4 ,
// Vnější hluk vozidla  dB(A)  - stojícího při ot   min⁻¹ ,Za jízdy,Nejvyšší rychlost  km h⁻¹ ,Poměr Výkon Hmotnost  kW kg⁻¹ ,
// Inovativní technologie,Stupeň dokončení,Faktor odchylky - DE,Faktor verifikace - Vf,Účel vozidla,Další záznamy,
// Alternativní provedení,Číslo TP,Číslo ORV,Druh RZ,Zařazení vozidla,Status,PČV,ABS,Airbag,ASR,Brzdy nouzová,
// Brzdy odlehčovací,Brzdy parkovací,Brzdy provozní,Doplňkový text na TP,Hmotnosti provozní Do,Hmotnosti zatížení SZ,
// Hmotnosti zatížení SZ typ,Hydropohon,Objem cisterny,Zatížení střechy,Číslo motoru,Nejvyšší rychlost omezení,Ovládání brzd SZ,
// Ovládání brzd SZ druh,Retarder,Rok výroby,Délka do,Ložná délka,Ložná šířka,Výška do,Typ kód,RM zániku,Stupeň autonomity vozidla
public partial class VypisVozidel
{
    [Name("PČV")]
    public string Pcv { get; set; }
    public string CheckSum { get; set; }

    [Name("Datum 1  registrace")]
    public DateOnly? Datum1Registrace { get; set; }
    [Name("Datum 1  registrace v ČR")]
    public DateOnly? Datum1RegistraceVCr { get; set; }
    [Name("ZTP")]
    public string Ztp { get; set; }
    [Name("ES EU")]
    public string EsEu { get; set; }
    [Name("Druh vozidla")]
    public string DruhVozidla { get; set; }
    [Name("Druh vozidla 2  ř ")]
    public string DruhVozidla2Radek { get; set; }
    [Name("Kategorie vozidla")]
    public string KategorieVozidla { get; set; }
    [Name("Tovární značka")]
    public string TovarniZnacka { get; set; }
    [Name("Typ")]
    public string Typ { get; set; }
    [Name("Varianta")]
    public string Varianta { get; set; }
    [Name("Verze")]
    public string Verze { get; set; }
    [Name("VIN")]
    public string Vin { get; set; }
    [Name("Obchodní označení")]
    public string ObchodniOznaceni { get; set; }

    [Name("Výrobce vozidla")]
    public string VyrobceVozidla { get; set; }
    [Name("Výrobce motoru")]
    public string VyrobceMotoru { get; set; }
    [Name("Typ motoru")]
    public string TypMotoru { get; set; }
    [Name("Max  výkon  kW     min⁻¹ ")]
    public string MaxVykonRaw { get; set; }

    public decimal? MaxVykon { get; set; }
    public decimal? Otacky { get; set; }

    [Name("Palivo")]
    public string Palivo { get; set; }
    [Name("Zdvihový objem  cm³ ")] //check
    public string ZdvihovyObjem { get; set; }
    [Name("Plně elektrické vozidlo")]
    [TypeConverter(typeof(AnoNeBooleanConverter))]
    public bool? PlneElektrickeVozidlo { get; set; }
    [Name("Hybridní vozidlo")]
    [TypeConverter(typeof(AnoNeBooleanConverter))]
    public bool? HybridniVozidlo { get; set; }
    [Name("Třída hybridního vozidla")]
    public string TridaHybridnihoVozidla { get; set; }
    [Name("Emisní limit  EHKOSN EHSES ")]
    public string EmisniLimitRaw { get; set; }

    public string PredpisEhkOsn { get; set; }

    public string PredpisEhsEsEu { get; set; }

    [Name("Stupeň plnění emisní úrovně")]
    public string StupenPlneniEmisniUrovne { get; set; }
    [Name("Korigovaný součinitel absorbce  m⁻¹ ")]
    public decimal? KorigovanySoucinitelAbsorpce { get; set; }
    [Name("CO2 město  mimo město kombinované  g km-1 ")]
    public string Co2Raw { get; set; }

    public decimal? Co2Mesto { get; set; }


    public decimal? Co2MimoMesto { get; set; }
    [Name("Specifické CO2")]
    public string SpecifickeCo2Raw { get; set; }
    [Name("Snížení emisí – NEDC")]
    public decimal? SnizeniEmisiNedc { get; set; }
    [Name("Snížení emisí – WLTP")]
    public decimal? SnizeniEmisiWltp { get; set; }
    [Name("Spotřeba předpis")]
    public string SpotrebaPredpis{ get; set; }
    [Name("Spotřeba město  mimo město kombinovaná  l 100km⁻¹ ")]
    public string SpotrebaRaw { get; set; }

    public decimal? SpotrebaMesto { get; set; }

    public decimal? SpotrebaMimoMesto { get; set; }

    public decimal? SpotrebaKombinovana { get; set; }
    [Name("Spotřeba při rychlosti  l 100 km⁻¹ ")]
    public string SpotrebaPriRychlosti{ get; set; }
    [Name("Spotřeba el  mobil  Wh km  – Z")]
    public decimal? SpotrebaElMobil { get; set; }
    [Name("Dojezd ZR  km ")]
    public decimal? DojezdZr { get; set; }
    [Name("Výrobce karoserie")]
    public string VyrobceKaroserie { get; set; }
    [Name("Druh (typ)")]
    public string DruhKaroserie { get; set; }
    [Name("Výrobní číslo karoserie")]
    public string VyrobniCisloKaroserie { get; set; }
    [Name("Barva")]
    public string Barva { get; set; }
    [Name("Barva doplňková")]
    public string BarvaDoplnkova { get; set; }

    [Name("Počet míst celkem   k sezení   k stání")]
    public string PocetMistRaw { get; set; }

    public decimal? PocetMistCelkem { get; set; }

    public decimal? PocetMistKSezeni { get; set; }

    public decimal? PocetMistKStani { get; set; }

    [Name("Celková délka šířka výška  mm ")]
    public string CelkovaDelkaSirkaVyskaRaw { get; set; }
    public decimal? Delka { get; set; }

    public decimal? Sirka { get; set; }

    public decimal? Vyska { get; set; }

    [Name("Rozchod  mm ")]
    public string RozchodRaw { get; set; }
    
    public decimal? Rozchod1 { get; set; }

    public decimal? Rozchod2 { get; set; }

    public decimal? Rozchod3 { get; set; }

    public decimal? Rozchod4 { get; set; }

    [Name("Rozvor  mm ")]
    public string RozvorRaw { get; set; }

    [Name("Provozní hmotnost")]
    public string ProvozniHmotnost { get; set; }

    [Name("Největší technicky přípustná povolená hmotnost  kg ")]
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostRaw { get; set; }
    public decimal? NejvetsiTechnickyPripustnaHmotnost { get; set; }

    [Name("Největší povolená hmotnost  kg ")]
    public decimal? NejvetsiTechnickyPovolenaHmotnost { get; set; }

    [Name("Největší technicky přípustná povolená hmotnost na nápravu  kg ")]
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuRaw { get; set; }
    
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN1 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN2 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN3 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN4 { get; set; }

    [Name("Největší povolená hmotnost na nápravu  kg ")]
    public string NejvetsiPovolenaHmotnostNaNapravuRaw { get; set; }
    public string NejvetsiPovolenaHmotnostNaNapravuN1 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN2 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN3 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN4 { get; set; }

    [Name("Největší technicky přípustná povolená hmotnost přípojného vozidla  kg  brzděného")]
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaBrzdeneRaw { get; set; }

    [Name("Největší technicky přípustná povolená hmotnost přípojného vozidla  kg  nebrzděného")]
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostPripojnehoVozidlaNebrzdeneRaw { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaBrzdene { get; set; }

    public decimal? NejvetsiPovolenaHmotnostPripojnehoVozidlaBrzdene { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaNeBrzdene { get; set; }

    public decimal? NejvetsiPovolenaHmotnostPripojnehoVozidlaNeBrzdene { get; set; }

    [Name("Největší technicky přípustná povolená hmotnost jízdní soupravy  kg ")]
    public string NejvetsiTechnickyPripustnaPovolenaHmotnostJizdniSoupravy { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostJizdniSoupravy { get; set; }

    public decimal? NejvetsiPovolenaHmotnostJizdniSoupravy { get; set; }

    [Name("Hmotnosti vozidla při testu WLTP")]
    public string HmotnostiVozidlaPriTestuWltp { get; set; }

    [Name("Průměrná hodnota užitečného zatížení")]
    public decimal? PrumernaHodnotaUzitecnehoZatizeni { get; set; }

    [Name("Spojovací zařízení - druh")]
    public string SpojovaciZarizeni { get; set; }

    [Name("Počet náprav - z toho poháněných")]
    public string PocetNapravRaw { get; set; }

    public decimal? PocetNaprav { get; set; }

    public string NapravPohanenych { get; set; }

    [Name("Kola a pneumatiky na nápravě - rozměry montáž  N 1; N 2; N 3; N 4 ")]
    public string KolaPneumatikyNapravyRaw { get; set; }
    
    public string PneumatikyNaprava1 { get; set; }

    public string PneumatikyNaprava2 { get; set; }

    public string PneumatikyNaprava3 { get; set; }

    public string PneumatikyNaprava4 { get; set; }

    public string KolaNaprava1 { get; set; }

    public string KolaNaprava2 { get; set; }

    public string KolaNaprava3 { get; set; }

    public string KolaNaprava4 { get; set; }

    [Name("Vnější hluk vozidla  dB(A)  - stojící při ot   min⁻¹ ")]
    public string VnejsiHlukVozidlaStojiciRaw { get; set; }

    public decimal? VnejsiHlukVozidlaStojici { get; set; }

    public decimal? VnejsiHlukVozidlaOtacky { get; set; }

    [Name("Za jízdy")]
    public string VnejsiHlukVozidlaZaJizdyRaw { get; set; }

    public decimal? VnejsiHlukVozidlaJizda { get; set; }

    [Name("Nejvyšší rychlost  km h⁻¹ ")]
    public decimal? NejvyssiRychlost { get; set; }

    [Name("Poměr Výkon Hmotnost  kW kg⁻¹ ")]
    public decimal? PomerVykonHmotnost { get; set; }

    public string PredpisSpotrebaPaliva { get; set; }

    [Name("Inovativní technologie")]
    public string InovativniTechnologie { get; set; }

    [Name("Stupeň dokončení")]
    public string StupenDokonceni { get; set; }
    [Name("Faktor odchylky - DE")]
    public decimal? FaktorOdchylkyDe { get; set; }

    [Name("Faktor verifikace - Vf")]
    public decimal? FaktorVerifikaceVf { get; set; }

    [Name("Dal39 z8znamy")]
    public string DalsiZaznamy { get; set; }
    [Name("Alternativní provedení")]
    public string AlternativniProvedeni { get; set; }
    [Name("Číslo TP")]
    public string CisloTp { get; set; }
    [Name("Číslo ORV")]
    public string CisloOrv { get; set; }
    
    public bool? ZadrzenoOrv { get; set; }
    [Name("Druh RZ")]
    public string DruhRz { get; set; }

    public bool? ZadrzenaRzPosledni { get; set; }
    [Name("Zařazení vozidla")]
    public string ZarazeniVozidla { get; set; }
    
    [Name("Status")]
    public string Status { get; set; }
    [Name("ABS")]
    public string Abs { get; set; }
    [Name("Airbag")]
    public string Airbag { get; set; }
    [Name("ASR")]
    public bool? Asr { get; set; }
    [Name("Brzdy nouzová")]
    public bool? BrzdyNouzova { get; set; }
    [Name("Brzdy odlehčovací")]
    public bool? BrzdyOdlehcovaci { get; set; }
    [Name("Brzdy parkovací")]
    public bool? BrzdyParkovaci { get; set; }
    [Name("Brzdy provozní")]
    public bool? BrzdyProvozni { get; set; }
    [Name("Doplňkový text na TP")]
    public string DoplňkovyTextNaTp { get; set; }
    [Name("Hmotnosti provozní Do")] //check
    public string HmotnostiProvozniDo { get; set; }
    [Name("Hmotnosti zatížení SZ")]
    public decimal? HmotnostiZatizeniSz { get; set; }
    [Name("Hmotnosti zatížení SZ typ")]
    public string HmotnostiZatizeniSzTyp { get; set; }
    [Name("Hydropohon")]
    public string Hydropohon { get; set; }
    [Name("Objem cisterny")]
    public string ObjemCisterny { get; set; }
    [Name("Zatížení střechy")]
    public string ZatizeniStrechy { get; set; }
    [Name("Číslo motoru")]
    public string CisloMotoru { get; set; }
    [Name("Nejvyšší rychlost omezení")]
    [TypeConverter(typeof(DecimalConverter))]
    public decimal? NejvyssiRychlostOmezeni { get; set; }
    [Name("Ovládání brzd SZ")]
    public string OvladaniBrzdSz { get; set; }
    [Name("Ovládání brzd SZ druh")]
    public string OvladaniBrzdSzDruh { get; set; }
    [Name("Retarder")]
    public bool? Retarder { get; set; }
    [Name("Rok výroby")]
    [TypeConverter(typeof(IntConverter))]
    
    public int? RokVyroby { get; set; }
   
    
    [Name("Délka do")] //check    
      public string DelkaDo { get; set; }
    [Name("Ložná délka")]
    public decimal? LoznaDelka { get; set; }
    [Name("Ložná šířka")]
    public decimal? LoznaSirka { get; set; }
    [Name("Výška do")] //check
    public string VyskaDo { get; set; }
    [Name("Typ kód")]
    public string TypKod { get; set; }
    [Name("Účel vozidla")]
    public string UcelVozidla { get; set; }
    [Name("RM zániku")]
    public string RmZaniku { get; set; }
    [Name("Stupeň autonomity vozidla")]
    public string StupenAutonomityVozidla { get; set; }
    [Ignore]
    public DateOnly LastUpdated { get; set; }
}