// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HlidacStatu.RegistrVozidel.Models;

public partial class VypisVozidel
{
    public string Pcv { get; set; }

    public DateOnly? Datum1Registrace { get; set; }

    public DateOnly? Datum1RegistraceVCr { get; set; }

    public string Ztp { get; set; }

    public string EsEu { get; set; }

    public string DruhVozidla { get; set; }

    public string DruhVozidla2Radek { get; set; }

    public string KategorieVozidla { get; set; }

    public string TovarniZnacka { get; set; }

    public string Typ { get; set; }

    public string Varianta { get; set; }

    public string Verze { get; set; }

    public string Vin { get; set; }

    public string ObchodniOznaceni { get; set; }

    public string VyrobceVozidla { get; set; }

    public string VyrobceMotoru { get; set; }

    public string TypMotoru { get; set; }

    public decimal? MaxVykon { get; set; }

    public decimal? Otacky { get; set; }

    public string Palivo { get; set; }

    public decimal? ZdvihovyObjem { get; set; }

    public bool? PlneElektrickeVozidlo { get; set; }

    public bool? HybridniVozidlo { get; set; }

    public string TridaHybridnihoVozidla { get; set; }

    public string PredpisEhkOsn { get; set; }

    public string PredpisEhsEsEu { get; set; }

    public string StupenPlneniEmisniUrovne { get; set; }

    public decimal? KorigovanySoucinitelAbsorpce { get; set; }

    public decimal? Co2 { get; set; }

    public decimal? Co2Mesto { get; set; }

    public decimal? Co2MimoMesto { get; set; }

    public decimal? SpecifickeCo2 { get; set; }

    public decimal? SnizeniEmisiNedc { get; set; }

    public decimal? SnizeniEmisiWltp { get; set; }

    public string SpotrebaPriRychlosti { get; set; }

    public decimal? SpotrebaMesto { get; set; }

    public decimal? SpotrebaMimoMesto { get; set; }

    public decimal? SpotrebaKombinovana { get; set; }

    public decimal? SpotrebaElMobil { get; set; }

    public decimal? DojezdZr { get; set; }

    public string VyrobceKaroserie { get; set; }

    public string DruhKaroserie { get; set; }

    public string VyrobniCisloKaroserie { get; set; }

    public string Barva { get; set; }

    public decimal? PocetMistCelkem { get; set; }

    public decimal? PocetMistKSezeni { get; set; }

    public decimal? PocetMistKStani { get; set; }

    public decimal? Delka { get; set; }

    public decimal? Sirka { get; set; }

    public decimal? Vyska { get; set; }

    public decimal? Rozchod1 { get; set; }

    public decimal? Rozchod2 { get; set; }

    public decimal? Rozchod3 { get; set; }

    public decimal? Rozchod4 { get; set; }

    public decimal? Rozvor { get; set; }

    public decimal? ProvozniHmotnost { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnost { get; set; }

    public decimal? NejvetsiTechnickyPovolenaHmotnost { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN1 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN2 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN3 { get; set; }

    public string NejvetsiTechnickyPripustnaPovolenaHmotnostNaNapravuN4 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN1 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN2 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN3 { get; set; }

    public string NejvetsiPovolenaHmotnostNaNapravuN4 { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaBrzdene { get; set; }

    public decimal? NejvetsiPovolenaHmotnostPripojnehoVozidlaBrzdene { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostPripojnehoVozidlaNeBrzdene { get; set; }

    public decimal? NejvetsiPovolenaHmotnostPripojnehoVozidlaNeBrzdene { get; set; }

    public decimal? NejvetsiTechnickyPripustnaHmotnostJizdniSoupravy { get; set; }

    public decimal? NejvetsiPovolenaHmotnostJizdniSoupravy { get; set; }

    public string HmotnostiVozidlaPriTestuWltp { get; set; }

    public decimal? PrumernaHodnotaUzitecnehoZatizeni { get; set; }

    public string SpojovaciZarizeni { get; set; }

    public decimal? PocetNaprav { get; set; }

    public string NapravPohanenych { get; set; }

    public string PneumatikyNaprava1 { get; set; }

    public string PneumatikyNaprava2 { get; set; }

    public string PneumatikyNaprava3 { get; set; }

    public string PneumatikyNaprava4 { get; set; }

    public string KolaNaprava1 { get; set; }

    public string KolaNaprava2 { get; set; }

    public string KolaNaprava3 { get; set; }

    public string KolaNaprava4 { get; set; }

    public decimal? VnejsiHlukVozidlaStojici { get; set; }

    public decimal? VnejsiHlukVozidlaOtacky { get; set; }

    public decimal? VnejsiHlukVozidlaJizda { get; set; }

    public decimal? NejvyssiRychlost { get; set; }

    public decimal? PomerVykonHmotnost { get; set; }

    public string PredpisSpotrebaPaliva { get; set; }

    public string InovativniTechnologie { get; set; }

    public string StupenDokonceni { get; set; }

    public decimal? FaktorOdchylkyDe { get; set; }

    public decimal? FaktorVerifikaceVf { get; set; }

    public string DalsiZaznamy { get; set; }

    public string AlternativniProvedeni { get; set; }

    public string CisloTp { get; set; }

    public string CisloOrv { get; set; }

    public bool? ZadrzenoOrv { get; set; }

    public string DruhRz { get; set; }

    public bool? ZadrzenaRzPosledni { get; set; }

    public string ZarazeniVozidla { get; set; }

    public DateOnly? PravidelnaTechnickaProhlidkaDo { get; set; }

    public DateOnly? EvidencniProhlidkaDne { get; set; }

    public string Status { get; set; }

    public bool? Abs { get; set; }

    public string Airbag { get; set; }

    public bool? Asr { get; set; }

    public bool? BrzdyNouzova { get; set; }

    public bool? BrzdyOdlehcovaci { get; set; }

    public bool? BrzdyParkovaci { get; set; }

    public bool? BrzdyProvozni { get; set; }

    public string DoplňkovyTextNaTp { get; set; }

    public decimal? HmotnostiProvozniDo { get; set; }

    public decimal? HmotnostiZatizeniSz { get; set; }

    public string HmotnostiZatizeniSzTyp { get; set; }

    public bool? Hydropohon { get; set; }

    public decimal? ObjemCisterny { get; set; }

    public string ZatizeniStrechy { get; set; }

    public string CisloMotoru { get; set; }

    public decimal? NejvyssiRychlostOmezeni { get; set; }

    public string OvladaniBrzdSz { get; set; }

    public string OvladaniBrzdSzDruh { get; set; }

    public bool? Retarder { get; set; }

    public decimal? RokVyroby { get; set; }

    public decimal? DelkaDo { get; set; }

    public decimal? LoznaDelka { get; set; }

    public decimal? LoznaSirka { get; set; }

    public decimal? VyskaDo { get; set; }

    public string TypKod { get; set; }

    public string UcelVozidla { get; set; }

    public string RmZaniku { get; set; }

    public DateOnly LastUpdated { get; set; }
}