using System;
using System.Collections.Generic;
public static class PU_OrganizaceTagsUploader
{
    
    private static List<(string Datovka, string Tagy)> _list = new()
    {
        ("cx2aize","bezpečnost"),
("84taiur","bezpečnost"),
("rrpd7zw","bezpečnost,policie,ředitelství"),
("rkiai5y","bezpečnost,policie,ředitelství"),
("eb8ai73","bezpečnost,policie,ředitelství"),
("jydai6g","bezpečnost,policie,ředitelství"),
("upshp5u","bezpečnost,policie,ředitelství"),
("x9nhptc","bezpečnost,policie,ředitelství"),
("urnai6d","bezpečnost,policie,ředitelství"),
("vsmhpv9","bezpečnost,policie,ředitelství"),
("n5hai7v","bezpečnost,policie,ředitelství"),
("6jwhpv6","bezpečnost,policie,ředitelství"),
("ndihp32","bezpečnost,policie,ředitelství"),
("5ixai69","bezpečnost,policie,ředitelství"),
("2dtai5u","bezpečnost,policie,ředitelství"),
("a64ai6n","bezpečnost,policie,ředitelství"),
("w6thp3w","bezpečnost,policie,ředitelství"),
("gyed7zz","bezpečnost,policie,vzduchoplavba"),
("hjyaavk","bezpečnost,ministerstvo"),
("kq4aawz","justice,ministerstvo"),
("6bnaawp","bezpečnost,ministerstvo"),
("bryj4t6","bezpečnost,policie,muzeum"),
("h93aayw","bezpečnost"),
("eesyd9x","bezpečnost,policie"),
("v2jdr7d","bezpečnost,policie"),
("zzfnkp3","bezpečnost,it"),
("kccaa9t","justice"),
("wwjaa4f","justice"),
("5smaetu","justice"),
("pyrd765","bezpečnost,policie"),
("gs9ai55","bezpečnost,policie"),
("raeaa5y","justice"),
("283d744","bezpečnost"),
("ybndqw9","bezpečnost,policie"),
("vtqabcz","justice"),
("7ruiypv","bezpečnost"),
("e7gd769","bezpečnost"),
("z2tadw5","justice"),
("sfsd748","bezpečnost"),
("yr2d762","bezpečnost,policie"),
("asgdrju","bezpečnost,policie"),
("b86abcb","bezpečnost"),
("2rsaa87","justice"),
("3fvabbh","justice"),
("ryhaa8a","justice"),
("uzcaety","justice"),
("7jckvi2","bezpečnost,armáda"),
("n62kuhr","bezpečnost,armáda"),
("7puaa4c","bezpečnost"),
("zr5efbb","centrální a kontrolní instituce"),
("8eqairg","centrální a kontrolní instituce"),
("rn6aas6","centrální a kontrolní instituce"),
("2gfaasy","centrální a kontrolní instituce"),
("a9qaats","centrální a kontrolní instituce"),
("uuaaatg","centrální a kontrolní instituce"),
("3umaayk","centrální a kontrolní instituce"),
("z49per3","centrální a kontrolní instituce"),
("96vaa2e","centrální a kontrolní instituce"),
("ybrxn8f","centrální a kontrolní instituce"),
("4iqaa3x","centrální a kontrolní instituce"),
("j2zaatn","centrální a kontrolní instituce"),
("x7cab34","centrální a kontrolní instituce"),
("4xr3pi6","centrální a kontrolní instituce"),
("d9fvd36","centrální a kontrolní instituce"),
("8edvryw","centrální a kontrolní instituce"),
("cmwaazf","centrální a kontrolní instituce"),
("me7aazb","centrální a kontrolní instituce"),
("qwfai2m","centrální a kontrolní instituce"),
("avraiqg","centrální a kontrolní instituce"),
("m3hgfmw","centrální a kontrolní instituce"),
("hgi42by","centrální a kontrolní instituce"),
("yt499qv","centrální a kontrolní instituce"),
("mmh6jtv","centrální a kontrolní instituce"),
("psn9irb","centrální a kontrolní instituce"),
("qkbaa2n","centrální a kontrolní instituce"),
("g7zais9","centrální a kontrolní instituce"),
("2fjadja","centrální a kontrolní instituce"),
("bykaigw","centrální a kontrolní instituce"),
("9hjaihw","centrální a kontrolní instituce"),
("44iaeqj","centrální a kontrolní instituce"),
("trfaa33","centrální a kontrolní instituce"),
("hkrkpwn","it"),
("jjqjqih","it"),
("yukd8p7","it"),
("txsvfsh","it"),
("vz5sbe3","doprava,české dráhy,železnice"),
("2kvzr6k","doprava,české dráhy,železnice,it"),
("s7xvk9s","doprava,železnice"),
("re9pc27","doprava,železnice"),
("dgzdjrp","doprava,české dráhy,železnice"),
("naadjrh","doprava,české dráhy,železnice"),
("8tscdpq","doprava,české dráhy,železnice"),
("w3jdjrd","doprava,české dráhy,železnice"),
("jyfbxtm","doprava,české dráhy,železnice"),
("7uudjr9","doprava,české dráhy,železnice"),
("zuqxd9j","doprava,české dráhy,železnice"),
("e52cdsf","doprava,české dráhy,železnice"),
("jcrdrqv","doprava,české dráhy,železnice"),
("tradr3j","doprava,české dráhy,železnice"),
("agnenry","doprava,české dráhy,železnice"),
("mkke4kb","doprava,české dráhy,železnice"),
("dnycves","doprava,české dráhy,železnice"),
("sdbfxh6","doprava,české dráhy,železnice,finance"),
("xaegchm","doprava,české dráhy,železnice"),
("m37gziu","doprava,české dráhy,železnice"),
("dihg7ip","doprava,české dráhy,železnice"),
("pzkgw87","doprava"),
("n75aau3","doprava,ministerstvo"),
("ttdv8hy","doprava,železnice"),
("zjq4rhz","doprava,železnice"),
("guqtubs","doprava,železnice"),
("uccchjm","doprava,železnice"),
("yhygbyn","doprava"),
("zchgzgr","doprava,výzkum,vzduchoplavba"),
("xhusbrm","doprava,vzduchoplavba"),
("ayqexy5","doprava,vzduchoplavba"),
("e5qaihb","doprava,finance"),
("yrfs29r","ostatní"),
("cq3xm56","ostatní"),
("sjfywke","ostatní"),
("buuenxj","ostatní"),
("drpizqr","ostatní"),
("a4we6rx","ostatní"),
("i6srzq8","ostatní"),
("rkga8r5","ostatní"),
("4x3ci67","ostatní"),
("nv8dknh","ostatní"),
("xz63f5t","ostatní"),
("mw6u68u","ostatní"),
("u25sd6f","zahraničí"),
("e4xaaxh","zahraničí,ministerstvo"),
("ifjp9k2","zahraničí"),
("kykkamx","zahraničí"),
("tj8vfp3","zahraničí"),
("49kaiq3","společnost"),
("wikaiz5","rozvoj,finance"),
("mt6427q","rozvoj"),
("yr9mzxx","rozvoj"),
("4ebr7ba","rozvoj"),
("26iaava","rozvoj,ministerstvo"),
("sc9aavg","společnost,práce,ministerstvo"),
("7hazk97","společnost,práce"),
("6zraazz","společnost"),
("u5yqf8d","společnost"),
("yi6jvet","výzkum,práce"),
("xy9n88n","výzkum,společnost"),
("nntwcis","finance,průmysl a obchod"),
("cyrj9gf","finance"),
("afrv7v6","finance"),
("8tgaiej","finance"),
("egi8zyh","finance"),
("p9iwj4f","finance,ředitelství"),
("qr9ab9x","finance"),
("xzeaauv","finance,ministerstvo"),
("bxtaaw4","průmysl a obchod,ministerstvo"),
("w9hdkyj","finance"),
("vszfqex","finance"),
("ag5uunk","finance"),
("7cs8cge","finance"),
("favab6q","finance,životní prostředí"),
("hqe39ah","finance"),
("jn2aiqd","finance"),
("fs2aa2t","průmysl a obchod"),
("6tnj224","finance"),
("nqkd2ia","finance"),
("4aydj3q","finance"),
("afth9xp","výzkum,průmysl a obchod"),
("ix6aa38","průmysl a obchod"),
("v8zvffd","výzkum"),
("a8uadk4","výzkum"),
("kr7cdry","služby,pošta"),
("f885sty","služby,pošta"),
("cwpykfh","služby,pošta"),
("dugmkm6","služby,armáda"),
("mjigh6r","služby"),
("ahem9gp","služby"),
("p8caixb","služby,archiv"),
("fe3aixh","služby,archiv"),
("yggktdp","služby"),
("6msaiwp","služby,archiv"),
("3gnaiva","služby,archiv"),
("b9xaiw4","služby,archiv"),
("k28aiwy","služby,archiv"),
("vuhaiws","služby,archiv"),
("48udtjq","služby"),
("v9deeqd","služby"),
("iazgiwe","služby"),
("yzmaix7","služby,archiv"),
("6r3afce","služby,archiv"),
("ir5hkiz","služby"),
("pssgys9","výzkum"),
("tquiv7d","vzdělávání"),
("nkr2ayv","vzdělávání"),
("5abj873","kultura"),
("cf2uiwg","vzdělávání"),
("6awdjrd","vzdělávání"),
("gg5aa56","vzdělávání"),
("8spaaur","kultura,ministerstvo"),
("vidaawt","vzdělávání,ministerstvo"),
("ddak8mr","kultura"),
("xpiqh6p","vzdělávání,knihovna"),
("bfi2vz4","kultura,muzeum"),
("iw39kef","kultura,muzeum"),
("nsm2bq4","kultura,muzeum"),
("f6d97sc","kultura,muzeum"),
("pn3cn9v","kultura,muzeum"),
("gidfxbg","kultura,muzeum"),
("qmbz5zc","kultura"),
("tg8i2zq","kultura"),
("wx3j85b","kultura"),
("vcwqfka","kultura"),
("5qt8sy8","vzdělávání,knihovna"),
("enbbt45","vzdělávání,knihovna"),
("gez6tzc","kultura,muzeum"),
("8xzf4vx","kultura,muzeum"),
("2cy8h6t","kultura"),
("hh6yjuw","kultura,muzeum"),
("8pswgy6","vzdělávání"),
("vnadiz2","finance,sport"),
("syd69w9","vzdělávání,knihovna"),
("f8vxca8","kultura,muzeum"),
("9rntqqk","kultura"),
("zx5ks9a","finance,sport"),
("afh2pbr","vzdělávání"),
("u5maa9p","vzdělávání,policie"),
("wfpqevq","kultura"),
("6nwqxf7","kultura,muzeum"),
("cmgp8ec","kultura,muzeum"),
("m86sw9i","kultura,muzeum"),
("zucgg9t","vzdělávání,policie"),
("hismuye","finance,sport"),
("nkbkgcb","vzdělávání,policie"),
("4zrkgbn","vzdělávání,policie"),
("6mjyx7i","kultura"),
("dbzaa4r","kultura"),
("q4fgwym","kultura,muzeum"),
("u4zgr6q","zdravotnictví"),
("f7eike4","zdravotnictví,výzkum"),
("it2qh79","zdravotnictví"),
("g4d3fvd","zdravotnictví,nemocnice"),
("nxwzf8e","zdravotnictví"),
("4twn9vt","zdravotnictví,nemocnice"),
("n9hiezm","zdravotnictví,nemocnice"),
("v7zqi84","zdravotnictví,nemocnice"),
("zizdbpb","zdravotnictví,nemocnice"),
("xa4krm2","zdravotnictví,nemocnice"),
("u2nmpm2","zdravotnictví,nemocnice"),
("pbvtj63","zdravotnictví,nemocnice"),
("h9tpjpn","zdravotnictví,nemocnice"),
("nk8bxj3","zdravotnictví,nemocnice"),
("asykkbj","zdravotnictví,nemocnice"),
("ptttufa","zdravotnictví,lázně"),
("zpqai2i","zdravotnictví,hygiena"),
("btgjvdm","zdravotnictví,nemocnice,výzkum"),
("ccgj4ai","zdravotnictví,nemocnice"),
("agzai3c","zdravotnictví,hygiena"),
("jaaai36","zdravotnictví,hygiena"),
("t3jai32","zdravotnictví,hygiena"),
("4uuai3w","zdravotnictví,hygiena"),
("dm5ai4r","zdravotnictví,hygiena"),
("nfeai4j","zdravotnictví,hygiena"),
("w8pai4f","zdravotnictví,hygiena"),
("7zyai4b","zdravotnictví,hygiena"),
("23wai86","zdravotnictví,hygiena"),
("samai8a","zdravotnictví,hygiena"),
("hhcai8e","zdravotnictví,hygiena"),
("8p3ai7n","zdravotnictví,hygiena"),
("xwsai7r","zdravotnictví,hygiena"),
("d6zp3nc","zdravotnictví,lázně"),
("42sj3nc","zdravotnictví,lázně"),
("7vqnyc6","zdravotnictví"),
("pv8aaxd","zdravotnictví,ministerstvo"),
("a55vw2c","zdravotnictví"),
("uehpcbb","zdravotnictví"),
("jb4gp8f","zdravotnictví,nemocnice"),
("7dqjigj","zdravotnictví"),
("r5yqkng","zdravotnictví"),
("wjqzqtn","zdravotnictví"),
("8w5389q","zdravotnictví,lázně"),
("zpfsmkk","zdravotnictví,lázně"),
("ymkj9r5","zdravotnictví"),
("xa6n85c","zdravotnictví"),
("ufhgx89","zdravotnictví,vzduchoplavba"),
("kb9egte","zdravotnictví"),
("b8mtp8k","zdravotnictví,nemocnice"),
("q6fwimp","zdravotnictví,nemocnice"),
("abkpz5n","zdravotnictví,nemocnice"),
("mdasj3u","zdravotnictví,nemocnice"),
("qyu26zz","zdravotnictví,nemocnice"),
("pubj9r8","zdravotnictví"),
("nf5j9jn","zdravotnictví"),
("eeuaau7","životní prostředí,energetika"),
("dkkdkdj","životní prostředí"),
("wjxibvp","životní prostředí"),
("siyhmun","životní prostředí"),
("e37djs6","životní prostředí"),
("65msw6w","životní prostředí"),
("e8jcfsn","životní prostředí"),
("yphaax8","zemědělství,ministerstvo"),
("9gsaax4","životní prostředí,ministerstvo"),
("dbyt8g2","životní prostředí,voda"),
("m49t8gw","životní prostředí,voda"),
("wwit8gq","životní prostředí,voda"),
("7ptt8gm","životní prostředí,voda"),
("gg4t8hf","životní prostředí,voda"),
("sxwrr4r","životní prostředí"),
("ssxrbr7","životní prostředí"),
("u85x3zd","životní prostředí"),
("5qur2qf","životní prostředí"),
("mmwuufk","životní prostředí"),
("6qsigjs","životní prostředí,energetika"),
("hq2aev4","životní prostředí,energetika"),
("d2vairv","zemědělství,veterina"),
("wwkdthw","zemědělství,veterina"),
("6kbndxj","zemědělství,veterina"),
("hizj7d7","zemědělství,veterina"),
("zdkaa2i","životní prostředí"),
("n5v4bry","životní prostředí"),
("ra7aipu","zemědělství,veterina"),
("v4gdarq","zemědělství,finance"),
("ugbaiq7","zemědělství"),
("bjds93z","životní prostředí"),
("5p7ua5u","výzkum,zemědělství"),
("77jfd47","výzkum,zemědělství,životní prostředí"),
("p96gp4k","výzkum,zemědělství"),
("3tnj7g7","výzkum,zemědělství"),
("69gngc7","výzkum,životní prostředí"),
("3gsnh8r","výzkum,zemědělství,veterina"),
("tqepb8z","výzkum,zemědělství,voda"),
("ce9zxhf","výzkum,zemědělství"),
("2fhnzkw","výzkum,zemědělství")
    };
    
    public static void CreateInserts()
    {

        foreach ((string Datovka, string Tagy) in _list)
        {
            foreach (var tag in Tagy.Split(",", StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
            {
                var insert =
                    $"INSERT INTO PU_OrganizaceTags (IdOrganizace, Tag) SELECT PU_Organizace.id, N'{tag}' FROM PU_Organizace WHERE PU_Organizace.DS = N'{Datovka.Trim()}';";
                Console.WriteLine(insert);
            }
        }

        

    }
}