using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgendyOVM.pusobnost_v_agendach
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using PusobnostRaw;
    //
    //    var coordinate = Coordinate.FromJson(jsonString);

    namespace Pusobnosti
    {
        using System;
        using System.Collections.Generic;

        using System.Globalization;

        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class Pusobnost
        {
            public string Id { get; set; }

            public string SubjektId { get; set; }

            public Registrace Registrace { get; set; }

            public Sluzby[] Sluzby { get; set; }

            public string Type { get; set; }

            public string[] Cinnosti { get; set; }
        }

        public partial class Registrace
        {
            public string Agenda { get; set; }

            public DateTime? Datum { get; set; }

            public string SubjektTyp { get; set; }

            public string Ovm { get; set; }

            public string Spuu { get; set; }
        }

        public partial class Sluzby
        {
            public string DuvodNeuvedeniPracovist { get; set; }

            public PracovisteStruct[] Pracoviste { get; set; }


            public SluzbaStruct Sluzba { get; set; }

            public class PracovisteStruct
            {
                public string PracovisteId { get; set; }
                public string Adresa { get; set; }
                public string AdresniMistoKod { get; set; }
                public string  Stat { get; set; }
            }

            public class SluzbaStruct
            {
                public string SluzbaId { get; set; }
                public string Nazev { get; set; }
                public string Popis { get; set; }
                public string TypSluzby { get; set; }
                public string Agenda { get; set; } //pouze kod
                public string[] Cinnosti { get; set; } //CinnostId

                public Ukony.Ukon[] Ukony { get; set; }

                 

            }
        }


        internal static class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                DateParseHandling = DateParseHandling.None,
                Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            };
        }
    }

}
