using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgendyOVM.pusobnost_v_agendach
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using PusobnostRaw;
    //
    //    var coordinate = Coordinate.FromJson(jsonString);

    namespace Pusobnosti
    {
        using System;
        using System.Collections.Generic;

        using System.Globalization;

        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class Raw
        {
            [JsonProperty("položky")]
            public PoložkyStruct[] Položky { get; set; }


            public partial class PoložkyStruct
            {
                [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
                public string Id { get; set; }

                [JsonProperty("registrace", NullValueHandling = NullValueHandling.Ignore)]
                public Registrace Registrace { get; set; }

                [JsonProperty("služby", NullValueHandling = NullValueHandling.Ignore)]
                public Sluzby[] Služby { get; set; }

                [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
                public string Type { get; set; }

                [JsonProperty("činnosti", NullValueHandling = NullValueHandling.Ignore)]
                public string[] Činnosti { get; set; }
            }

            public partial class Registrace
            {
                [JsonProperty("agenda", NullValueHandling = NullValueHandling.Ignore)]
                public string Agenda { get; set; }

                [JsonProperty("datum", NullValueHandling = NullValueHandling.Ignore)]
                public DateTimeOffset? Datum { get; set; }

                [JsonProperty("ovm", NullValueHandling = NullValueHandling.Ignore)]
                public string Ovm { get; set; }

                [JsonProperty("spuú", NullValueHandling = NullValueHandling.Ignore)]
                public string Spuú { get; set; }
            }

            public partial class Sluzby
            {
                [JsonProperty("důvod-neuvedení-pracovišť", NullValueHandling = NullValueHandling.Ignore)]
                public string DůvodNeuvedeníPracovišť { get; set; }

                [JsonProperty("pracoviště", NullValueHandling = NullValueHandling.Ignore)]
                public string[] Pracoviště { get; set; }

                [JsonProperty("služba", NullValueHandling = NullValueHandling.Ignore)]
                public string Služba { get; set; }
            }

        }
    }
}
